-- SC003010 設通検索一覧の最大件数取得SQL
SELECT 
	COUNT(*) 
FROM (
	SELECT DISTINCT 
		ECS.ECS_NO,
		ECS.ECS_REV_NO
	FROM TB003001 ECS
	LEFT JOIN TB003002 SIMUL_ECS
	ON
		ECS.ECS_NO = SIMUL_ECS.SIMULTANEOUS_ECS_NO AND 
		-- 改訂は正しい結合ではないが、理論上は合致する
		ECS.ECS_REV_NO = SIMUL_ECS.REPR_ECS_REV_NO AND
		ECS.REPR_SIMUL_CLASS = :SIMUL_CLS
	LEFT JOIN TB003007 ECS_MT
	ON
		ECS.ECS_NO = ECS_MT.ECS_NO AND
		ECS.ECS_REV_NO = ECS_MT.ECS_REV_NO
	LEFT JOIN TB003009 ECS_ISSUE
	ON
		ECS.ECS_NO = ECS_ISSUE.ECS_NO AND
		ECS.ECS_REV_NO = ECS_ISSUE.ECS_REV_NO
	LEFT JOIN TB004001 FPN
	ON
		DECODE(ECS.REPR_SIMUL_CLASS,:SIMUL_CLS,SIMUL_ECS.REPR_ECS_NO,ECS.ECS_NO) = FPN.REPR_OF_MAIN_ECS_NO AND
		FPN.SKIP_FLAG = '0'
	-- 関連部品のタイプ=Fと外部結合
	LEFT JOIN TB001005 RP 
	ON
		FPN.PARTS_NO = RP.PARTS_NO AND RP.RELATION_TYPE = 'F'
	-- 関連部品のタイプ=Fの部品諸元を取得
	LEFT JOIN TB001003 EPN_F
	ON
		EPN_F.PARTS_NO = RP.RELATED_PARTS_NO AND
		EPN_F.PARTS_PROP_REV_NO IN (SELECT MAX(TEPN_F.PARTS_PROP_REV_NO) FROM TB001003 TEPN_F WHERE TEPN_F.PARTS_NO = RP.RELATED_PARTS_NO GROUP BY TEPN_F.PARTS_NO)
	-- 自部品のタイプの部品諸元を取得
	LEFT JOIN TB001003 EPN
	ON
		FPN.PARTS_NO = EPN.PARTS_NO AND
		FPN.PARTS_PROP_REV_NO = EPN.PARTS_PROP_REV_NO
	LEFT JOIN TB009005 BLK
	ON
		CASE 
			WHEN RP.RELATED_PARTS_NO IS NULL THEN EPN.DRAWING_BLOCK_NO
			ELSE EPN_F.DRAWING_BLOCK_NO
		END = BLK.BLOCK_NO 
	WHERE 
		-- 設通受領日が指定された場合
		ECS.RECEIVED_DATE >= :INPUT_DATE_FROM AND
		ECS.RECEIVED_DATE <= :INPUT_DATE_TO AND
		-- 設審日が指定された場合
		ECS_MT.ECS_MEETING_DATE >= :INPUT_DATE_FROM AND
		ECS_MT.ECS_MEETING_DATE <= :INPUT_DATE_TO AND
		ECS_MT.ECS_MTG_LOCATION = :INPUT_LOC AND
		-- 発行日が指定された場合
		ECS_ISSUE.ECS_ISSUE_DATE >= :INPUT_DATE_FROM AND
		ECS_ISSUE.ECS_ISSUE_DATE <= :INPUT_DATE_TO AND
		-- 設通シリーズが指定された場合
		ECS.ECS_SERIES = :INPUT_SERIES AND
		-- 課コードが指定された場合
		ECS.SECTION_CODE IN (:INPUT_SEC_CD) AND
		-- 一連NOが指定された場合
		ECS.SERIAL_NO LIKE CONCAT(:INPUT_SER_NO,'%') AND
		-- 改訂NOが指定された場合
		ECS.ECS_REV_NO = :INPUT_REV_NO AND
		-- ブロックNOが指定された場合
		CASE 
			WHEN RP.RELATED_PARTS_NO IS NULL THEN
				EPN.DRAWING_BLOCK_NO
			ELSE
				EPN_F.DRAWING_BLOCK_NO
		END LIKE CONCAT(:INPUT_BLOCK_NO,'%') AND						-- ブロックNO
		-- ブロック担当者が指定された場合
		BLK.USER_ID = :INPUT_USER_ID AND
		-- 発行済は表示しないが指定された場合
		ECS.ECS_STATUS <> :ECS_STATUS_ISSUED AND
		-- 要注意が指定された場合
		ECS.ATTENTION = :INPUT_ATTENTION AND
		-- 先行発行が指定された場合
		ECS.PRECEDE_FLAG = :INPUT_PRECEDE AND
		-- 手配区分が指定された場合
		ECS.ARRANGE_CLASS = :INPUT_ARRANGE_CLS AND
		-- 設通ステータスが指定された場合
		ECS.ECS_STATUS = :INPUT_ECS_STATUS AND
		-- 実施時期未決の設通のみを表示が指定された場合
		ECS.ECS_STATUS = :ECS_STATUS_EXAMINATION_TBD AND
		-- 代表設通のみを表示が指定された場合
		ECS.REPR_SIMUL_CLASS = :REPR_SIMUL_CLA_REPR
) X

