--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "TB003008" (
		"ECS_NO" CHAR(11) NOT NULL, 
		"ECS_REV_NO" CHAR(1) NOT NULL, 
		"APPLIED_MODEL_CODE" CHAR(5) NOT NULL, 
		"DESTINATION" CHAR(1) NOT NULL, 
		"IMPL_DATE_INPUT_COL" CHAR(1) NOT NULL, 
		"APPLIED_MODEL" CHAR(3) NOT NULL, 
		"ECS_IMPL_REV_NO" CHAR(3) NOT NULL, 
		"DISPLAY_ORDER" SMALLINT NOT NULL, 
		"DGN_REQD_START_DATE" CHAR(2) NOT NULL, 
		"ARR_REQD_START_DATE" CHAR(2) NOT NULL, 
		"DECIDED_IMPL_DATE" DATE NOT NULL, 
		"PARTIAL_PENDING_FLAG" CHAR(1) NOT NULL, 
		"PENDING_DECIDED_DATE" DATE NOT NULL, 
		"IMPLEMENT_EVENT_ID" CHAR(6) NOT NULL, 
		"ECS_ISSUE_DATE" DATE NOT NULL, 
		"IMPL_DATE_DECIDED_DATE" DATE NOT NULL, 
		"ECS_MEETING_DATE" DATE NOT NULL, 
		"ECS_MTG_DATE_STATUS" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009004" (
		"APPLIED_MODEL_CODE" CHAR(5) NOT NULL, 
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009009" (
		"APPLIED_MODEL_CODE" CHAR(5) NOT NULL, 
		"DESTINATION" CHAR(1) NOT NULL, 
		"IMPL_DATE_INPUT_COL" CHAR(1) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "TB003008" ADD CONSTRAINT "TB003008_PK" PRIMARY KEY
	("ECS_NO", 
	 "ECS_REV_NO", 
	 "APPLIED_MODEL_CODE", 
	 "DESTINATION", 
	 "IMPL_DATE_INPUT_COL", 
	 "APPLIED_MODEL", 
	 "ECS_IMPL_REV_NO");

ALTER TABLE "TB009004" ADD CONSTRAINT "TB009004_PK" PRIMARY KEY
	("APPLIED_MODEL_CODE");

ALTER TABLE "TB009009" ADD CONSTRAINT "TB009009_PK" PRIMARY KEY
	("APPLIED_MODEL_CODE", 
	 "DESTINATION", 
	 "IMPL_DATE_INPUT_COL");

