--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "TB001004" (
		"PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"SUB_PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PS_REV_NO" CHAR(3) NOT NULL, 
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"START_DATE" DATE NOT NULL, 
		"END_DATE" DATE NOT NULL, 
		"DRAWING_OVER" CHAR(1) NOT NULL, 
		"DRAWING_SYMBOL" CHAR(1) NOT NULL, 
		"INDEX" CHAR(2) NOT NULL, 
		"KIND" CHAR(1) NOT NULL, 
		"DWG_JDG_CODE" CHAR(1) NOT NULL, 
		"REFERENCE" CHAR(1) NOT NULL, 
		"PS_NAME" CHAR(20) NOT NULL, 
		"QUANTITY" SMALLINT NOT NULL, 
		"DOMESTIC_CAL_CODE" CHAR(1) NOT NULL, 
		"FOREIGN_CAL_CODE" CHAR(1) NOT NULL, 
		"CKD_CLASS" CHAR(1) NOT NULL, 
		"THICKNESS" CHAR(5) NOT NULL, 
		"MATERIAL" VARCHAR(48) NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"REPR_OF_MAIN_ECS_NO" CHAR(11) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003001" (
		"ECS_NO" CHAR(11) NOT NULL, 
		"ECS_REV_NO" CHAR(1) NOT NULL, 
		"ECS_SERIES" CHAR(4) NOT NULL, 
		"SECTION_CODE" CHAR(1) NOT NULL, 
		"SERIAL_NO" CHAR(4) NOT NULL, 
		"REPR_SIMUL_CLASS" CHAR(1) NOT NULL, 
		"ECS_TITLE_JP" VARCHAR(250) NOT NULL, 
		"ECS_TITLE_EN" VARCHAR(300) NOT NULL, 
		"ECS_STATUS" CHAR(2) NOT NULL, 
		"ECS_PUBLIC_STATUS" CHAR(2) NOT NULL, 
		"PRECEDE_FLAG" CHAR(1) NOT NULL, 
		"DESIGN_DEPARTMENT" VARCHAR(30) NOT NULL, 
		"DESIGN_SECTION" VARCHAR(30) NOT NULL, 
		"ARRANGE_CLASS" CHAR(1) NOT NULL, 
		"ATTENTION" CHAR(1) NOT NULL, 
		"URGENCY" CHAR(1) NOT NULL, 
		"DISTRIBUTE_CLASS" CHAR(30) NOT NULL, 
		"APPLIED_MODEL" CHAR(30) NOT NULL, 
		"VEHICLE_CHECK" CHAR(1) NOT NULL, 
		"EG_TM_CHECK" CHAR(1) NOT NULL, 
		"REASON" CHAR(1) NOT NULL, 
		"IMPORTANCE" CHAR(1) NOT NULL, 
		"SYNCHRONOUS_CHANGE" CHAR(1) NOT NULL, 
		"RECEIVED_DATE" DATE NOT NULL, 
		"OVERFLOW_REPR_ECS_NO" CHAR(11) NOT NULL, 
		"ECS_ISSUE_DATE" DATE NOT NULL, 
		"GJ_ECS_RECEIVE_DATE" DATE NOT NULL, 
		"ECS_ISSUE_MEMBER" CHAR(20) NOT NULL, 
		"DESIGN_PHONE_NO" CHAR(4) NOT NULL, 
		"REGULATION" CHAR(7) NOT NULL, 
		"EC_DEMAND_DEPT" CHAR(20) NOT NULL, 
		"EC_APPLY" CHAR(1) NOT NULL, 
		"ARRANGE_REMARKS" VARCHAR(3000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004006" (
		"BATCH_UNIQUE_KEY" VARCHAR(40) NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PN_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PN_REV_NO" CHAR(3) NOT NULL, 
		"ERROR_GROUP_NO" SMALLINT NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004007" (
		"BATCH_UNIQUE_KEY" VARCHAR(40) NOT NULL, 
		"SEAQUENCE" SMALLINT NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PN_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PN_REV_NO" CHAR(3) NOT NULL, 
		"SUB_PARTS_NO" CHAR(15) NOT NULL, 
		"PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"PS_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PS_REV_NO" CHAR(3) NOT NULL, 
		"REPR_OF_MAIN_ECS_NO" CHAR(11) NOT NULL, 
		"ERROR_MESSAGE" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006008" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"PARTS_NAME" CHAR(20) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"USER_ID" CHAR(10) NOT NULL, 
		"FUNCTION" CHAR(5) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007002" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"COL_NO" SMALLINT NOT NULL, 
		"WORK_ORDER_NO" CHAR(10) NOT NULL, 
		"MODEL_CODE" CHAR(7) NOT NULL, 
		"SELECT_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007003" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"LINE_NO" SMALLINT NOT NULL, 
		"MODEL" CHAR(4) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"WORK_NO" CHAR(10) NOT NULL, 
		"LINE_ID" CHAR(3) NOT NULL, 
		"CONTROL_NO" CHAR(4) NOT NULL, 
		"SPECIAL_MARK" CHAR(1) NOT NULL, 
		"HISTORY" CHAR(1) NOT NULL, 
		"LEVEL" SMALLINT NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"REV_NO" CHAR(2) NOT NULL, 
		"PARTS_NAME" VARCHAR(20) NOT NULL, 
		"PURCHASER" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PREPARATION" CHAR(1) NOT NULL, 
		"MAN_HOUR" CHAR(1) NOT NULL, 
		"QUANTITY" CHAR(80) NOT NULL, 
		"DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"CAL_CODE" CHAR(1) NOT NULL, 
		"SIA_CAL_CODE" CHAR(1) NOT NULL, 
		"CKD_CLASS" CHAR(1) NOT NULL, 
		"MASS" VARCHAR(6) NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"FIRST_MODEL_DUE_DATE" DATE NOT NULL, 
		"DELIVERY_QUANTITY" SMALLINT NOT NULL, 
		"ARRANGEMENT_SIGN" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"REV_REMARKS" VARCHAR(600) NOT NULL, 
		"MATERIAL_DESCRIPTION" VARCHAR(48) NOT NULL, 
		"DWG_ISSUE_PLAN_DATE" DATE NOT NULL, 
		"CONTENTS" CHAR(6) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007004" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"EVENT_MODEL_CODE" CHAR(7) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007005" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"LINE_ID" CHAR(3) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"MODEL" CHAR(4) NOT NULL, 
		"WORK_NO" CHAR(10) NOT NULL, 
		"CONTROL_NO" CHAR(4) NOT NULL, 
		"SPECIAL_MARK" CHAR(1) NOT NULL, 
		"HISTORY" CHAR(1) NOT NULL, 
		"LEVEL" SMALLINT NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"REV_NO" CHAR(2) NOT NULL, 
		"PARTS_NAME" CHAR(20) NOT NULL, 
		"PURCHASER" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PREPARATION" CHAR(1) NOT NULL, 
		"MAN_HOUR" CHAR(1) NOT NULL, 
		"DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"CAL_CODE" CHAR(1) NOT NULL, 
		"SIA_CAL_CODE" CHAR(1) NOT NULL, 
		"CKD_CLASS" CHAR(1) NOT NULL, 
		"FIRST_MODEL_DUE_DATE" DATE NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"ARRANGEMENT_SIGN" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"REV_REMARKS" VARCHAR(600) NOT NULL, 
		"MATERIAL_DESCRIPTION" VARCHAR(48) NOT NULL, 
		"DWG_ISSUE_PLAN_DATE" DATE NOT NULL, 
		"MFG_SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"MFG_DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"MFG_DUE_DATE" DATE NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007008" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"LEVEL" SMALLINT NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"DUE_DATE" DATE NOT NULL, 
		"SUMMARY_SYMBOL" CHAR(1) NOT NULL, 
		"CHANGE_REV_NO" CHAR(3) NOT NULL, 
		"TRL_CHANGE_SYMBOL" CHAR(1) NOT NULL, 
		"MFG_CHANGE_SYMBOL" CHAR(1) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"SPECIAL_MARK" CHAR(1) NOT NULL, 
		"PURCHASER" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PARTS_NAME" CHAR(20) NOT NULL, 
		"TRL_SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"PARTS_REV_NO" CHAR(3) NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"TRL_DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"DWG_PARTS_NO" CHAR(15) NOT NULL, 
		"DWG_PARTS_REV_NO" CHAR(3) NOT NULL, 
		"DWG_ECS_NO" CHAR(11) NOT NULL, 
		"DWG_SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"DWG_CONS_ROUT" VARCHAR(100) NOT NULL, 
		"PRD_QLT_REMARKS" VARCHAR(600) NOT NULL, 
		"CAL_CODE" CHAR(1) NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"CKD_CLASS" CHAR(1) NOT NULL, 
		"ARRANGEMENT_SIGN" CHAR(1) NOT NULL, 
		"CHANGE_REASON" VARCHAR(600) NOT NULL, 
		"DISPLAY_ORDER" SMALLINT NOT NULL, 
		"FUNCTION" CHAR(5) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007012" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"CHANGE_REV_NO" CHAR(3) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009009" (
		"APPLIED_MODEL_CODE" CHAR(4) NOT NULL, 
		"DESTINATION" CHAR(1) NOT NULL, 
		"IMPL_DATE_INPUT_COL" CHAR(1) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011002" (
		"USER_ID" CHAR(10) NOT NULL, 
		"EMPLOYEE_NO" CHAR(8) NOT NULL, 
		"KANJI_NAME" VARCHAR(30) NOT NULL, 
		"ROMAN_NAME" VARCHAR(60) NOT NULL, 
		"KANA_NAME" VARCHAR(60) NOT NULL, 
		"ORGANIZATION_CODE" CHAR(6) NOT NULL, 
		"E_MAIL_ADDRESS" VARCHAR(256) NOT NULL, 
		"PHONE_NO" CHAR(15) NOT NULL, 
		"LANGUAGE_CODE" CHAR(2) NOT NULL, 
		"ROLE_ID" CHAR(10) NOT NULL, 
		"AUTO_DEL_EXCEPT_FLAG" CHAR(6) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATE_UPDATE_DATE" DATE NOT NULL, 
		"AUTH_STOP_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"SESSION_ID" VARCHAR(104) NOT NULL, 
		"LOGIN_TIME" TIMESTAMP NOT NULL, 
		"LOGOUT_TIME" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "TB001004" ADD CONSTRAINT "TB001004_PK" PRIMARY KEY
	("PARENT_PARTS_NO", 
	 "SUB_PARTS_NO", 
	 "ENGINEERING_PS_REV_NO");

ALTER TABLE "TB003001" ADD CONSTRAINT "TB003001_PK" PRIMARY KEY
	("ECS_REV_NO", 
	 "ECS_NO");

ALTER TABLE "TB004006" ADD CONSTRAINT "TB004006_PK" PRIMARY KEY
	("BATCH_UNIQUE_KEY", 
	 "PARTS_NO", 
	 "ENGINEERING_PN_REV_NO", 
	 "FACTORY_PN_REV_NO");

ALTER TABLE "TB004007" ADD CONSTRAINT "TB004007_PK" PRIMARY KEY
	("BATCH_UNIQUE_KEY", 
	 "SEAQUENCE");

ALTER TABLE "TB006008" ADD CONSTRAINT "TB006008_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "PARTS_NO", 
	 "PARTS_NAME", 
	 "BLOCK_NO", 
	 "SUPPLIER_CODE", 
	 "USER_ID");

ALTER TABLE "TB007002" ADD CONSTRAINT "TB007002_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "REV_NOTIFY_NO", 
	 "COL_NO");

ALTER TABLE "TB007003" ADD CONSTRAINT "TB007003_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "REV_NOTIFY_NO", 
	 "LINE_NO");

ALTER TABLE "TB007004" ADD CONSTRAINT "TB007004_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "EVENT_MODEL_CODE");

ALTER TABLE "TB007005" ADD CONSTRAINT "TB007005_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "BLOCK_NO", 
	 "EVENT_PARTS_NO", 
	 "LINE_ID", 
	 "REV_NOTIFY_NO");

ALTER TABLE "TB007008" ADD CONSTRAINT "TB007008_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "BLOCK_NO", 
	 "LEVEL", 
	 "EVENT_PARTS_NO", 
	 "SUPPLY_SECTION", 
	 "DELIVERY_LOCATION", 
	 "DUE_DATE", 
	 "SUMMARY_SYMBOL", 
	 "CHANGE_REV_NO");

ALTER TABLE "TB007012" ADD CONSTRAINT "TB007012_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "REV_NOTIFY_NO", 
	 "SHEET_CODE");

ALTER TABLE "TB009009" ADD CONSTRAINT "TB009009_PK" PRIMARY KEY
	("APPLIED_MODEL_CODE", 
	 "DESTINATION", 
	 "IMPL_DATE_INPUT_COL");

ALTER TABLE "TB011002" ADD CONSTRAINT "TB011002_PK" PRIMARY KEY
	("USER_ID");

CREATE VIEW "VW005001" AS
--ï ìYVW005001.sqléQè∆ÅB;
