--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "TB007001" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007002" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"COL_NO" SMALLINT NOT NULL, 
		"WORK_ORDER_NO" CHAR(10) NOT NULL, 
		"MODEL_CODE" CHAR(7) NOT NULL, 
		"SELECT_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007003" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"LINE_NO" SMALLINT NOT NULL, 
		"MODEL" CHAR(4) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"WORK_NO" CHAR(10) NOT NULL, 
		"LINE_ID" CHAR(3) NOT NULL, 
		"CONTROL_NO" CHAR(4) NOT NULL, 
		"SPECIAL_MARK" CHAR(1) NOT NULL, 
		"HISTORY" CHAR(1) NOT NULL, 
		"LEVEL" SMALLINT NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"REV_NO" CHAR(2) NOT NULL, 
		"PARTS_NAME" VARCHAR(20) NOT NULL, 
		"PURCHASER" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PREPARATION" CHAR(1) NOT NULL, 
		"MAN_HOUR" CHAR(1) NOT NULL, 
		"QUANTITY" CHAR(80) NOT NULL, 
		"DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"CAL_CODE" CHAR(1) NOT NULL, 
		"SIA_CAL_CODE" CHAR(1) NOT NULL, 
		"CKD_CLASS" CHAR(1) NOT NULL, 
		"MASS" VARCHAR(6) NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"FIRST_MODEL_DUE_DATE" DATE NOT NULL, 
		"DELIVERY_QUANTITY" SMALLINT NOT NULL, 
		"ARRANGEMENT_SIGN" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"REV_REMARKS" VARCHAR(600) NOT NULL, 
		"MATERIAL_DESCRIPTION" VARCHAR(48) NOT NULL, 
		"DWG_ISSUE_PLAN_DATE" DATE NOT NULL, 
		"CONTENTS" CHAR(6) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007004" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"EVENT_MODEL_CODE" CHAR(7) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007005" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"LINE_ID" CHAR(3) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"MODEL" CHAR(4) NOT NULL, 
		"WORK_NO" CHAR(10) NOT NULL, 
		"CONTROL_NO" CHAR(4) NOT NULL, 
		"SPECIAL_MARK" CHAR(1) NOT NULL, 
		"HISTORY" CHAR(1) NOT NULL, 
		"LEVEL" SMALLINT NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"REV_NO" CHAR(2) NOT NULL, 
		"PARTS_NAME" CHAR(20) NOT NULL, 
		"PURCHASER" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PREPARATION" CHAR(1) NOT NULL, 
		"MAN_HOUR" CHAR(1) NOT NULL, 
		"DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"CAL_CODE" CHAR(1) NOT NULL, 
		"SIA_CAL_CODE" CHAR(1) NOT NULL, 
		"CKD_CLASS" CHAR(1) NOT NULL, 
		"FIRST_MODEL_DUE_DATE" DATE NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"ARRANGEMENT_SIGN" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"REV_REMARKS" VARCHAR(600) NOT NULL, 
		"MATERIAL_DESCRIPTION" VARCHAR(48) NOT NULL, 
		"DWG_ISSUE_PLAN_DATE" DATE NOT NULL, 
		"MFG_SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"MFG_DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"MFG_DUE_DATE" DATE NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007006" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"LINE_ID" CHAR(3) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"EVENT_MODEL_CODE" CHAR(7) NOT NULL, 
		"QUANTITY" SMALLINT NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007007" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"CHANGE_REV_NO" CHAR(3) NOT NULL, 
		"CHANGE_STATUS" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007008" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"LEVEL" SMALLINT NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"DUE_DATE" DATE NOT NULL, 
		"SUMMARY_SYMBOL" CHAR(1) NOT NULL, 
		"CHANGE_REV_NO" CHAR(3) NOT NULL, 
		"TRL_CHANGE_SYMBOL" CHAR(1) NOT NULL, 
		"MFG_CHANGE_SYMBOL" CHAR(1) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"SPECIAL_MARK" CHAR(1) NOT NULL, 
		"PURCHASER" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PARTS_NAME" CHAR(20) NOT NULL, 
		"TRL_SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"PARTS_REV_NO" CHAR(3) NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"TRL_DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"DWG_PARTS_NO" CHAR(15) NOT NULL, 
		"DWG_PARTS_REV_NO" CHAR(3) NOT NULL, 
		"DWG_ECS_NO" CHAR(11) NOT NULL, 
		"DWG_SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"DWG_CONS_ROUT" VARCHAR(100) NOT NULL, 
		"PRD_QLT_REMARKS" VARCHAR(600) NOT NULL, 
		"CAL_CODE" CHAR(1) NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"CKD_CLASS" CHAR(1) NOT NULL, 
		"ARRANGEMENT_SIGN" CHAR(1) NOT NULL, 
		"CHANGE_REASON" VARCHAR(600) NOT NULL, 
		"DISPLAY_ORDER" SMALLINT NOT NULL, 
		"FUNCTION" CHAR(5) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007009" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"LEVEL" SMALLINT NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"DUE_DATE" DATE NOT NULL, 
		"SUMMARY_SYMBOL" CHAR(1) NOT NULL, 
		"CHANGE_REV_NO" CHAR(3) NOT NULL, 
		"EVENT_MODEL_CODE" CHAR(7) NOT NULL, 
		"QUANTITY" SMALLINT NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007010" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"TRL_SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"MFG_SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007011" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"TRL_DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"MFG_DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"DUE_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007012" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"CHANGE_REV_NO" CHAR(3) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "TB007001" ADD CONSTRAINT "TB007001_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID");

ALTER TABLE "TB007002" ADD CONSTRAINT "TB007002_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "REV_NOTIFY_NO", 
	 "COL_NO");

ALTER TABLE "TB007003" ADD CONSTRAINT "TB007003_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "REV_NOTIFY_NO", 
	 "LINE_NO");

ALTER TABLE "TB007004" ADD CONSTRAINT "TB007004_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "EVENT_MODEL_CODE");

ALTER TABLE "TB007005" ADD CONSTRAINT "TB007005_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "BLOCK_NO", 
	 "EVENT_PARTS_NO", 
	 "LINE_ID", 
	 "REV_NOTIFY_NO");

ALTER TABLE "TB007006" ADD CONSTRAINT "TB007006_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "BLOCK_NO", 
	 "EVENT_PARTS_NO", 
	 "LINE_ID", 
	 "REV_NOTIFY_NO", 
	 "EVENT_MODEL_CODE");

ALTER TABLE "TB007007" ADD CONSTRAINT "TB007007_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "CHANGE_REV_NO");

ALTER TABLE "TB007008" ADD CONSTRAINT "TB007008_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "BLOCK_NO", 
	 "LEVEL", 
	 "EVENT_PARTS_NO", 
	 "SUPPLY_SECTION", 
	 "DELIVERY_LOCATION", 
	 "DUE_DATE", 
	 "SUMMARY_SYMBOL", 
	 "CHANGE_REV_NO");

ALTER TABLE "TB007009" ADD CONSTRAINT "TB007009_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "BLOCK_NO", 
	 "LEVEL", 
	 "EVENT_PARTS_NO", 
	 "SUPPLY_SECTION", 
	 "DELIVERY_LOCATION", 
	 "DUE_DATE", 
	 "SUMMARY_SYMBOL", 
	 "CHANGE_REV_NO", 
	 "EVENT_MODEL_CODE");

ALTER TABLE "TB007010" ADD CONSTRAINT "TB007010_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID");

ALTER TABLE "TB007011" ADD CONSTRAINT "TB007011_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID");

ALTER TABLE "TB007012" ADD CONSTRAINT "TB007012_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "REV_NOTIFY_NO", 
	 "SHEET_CODE");

