--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "TB004001" (
		"PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PN_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PN_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PN_STATUS" CHAR(2) NOT NULL, 
		"APPROVED_DATE" DATE NOT NULL, 
		"APPROVER_USER_ID" CHAR(10) NOT NULL, 
		"EDITOR_USER_ID" CHAR(10) NOT NULL, 
		"ADOPT_DATE" DATE NOT NULL, 
		"ABOLISH_DATE" DATE NOT NULL, 
		"TMP_REGIST_DATE" DATE NOT NULL, 
		"PENDING_DECIDED_DATE" DATE NOT NULL, 
		"JOB_SEQ_NO" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PROD_BASE_CODE" CHAR(1) NOT NULL, 
		"DATA_CHECK_RESULT" CHAR(1) NOT NULL, 
		"REPR_OF_MAIN_ECS_NO" CHAR(11) NOT NULL, 
		"SKIP_FLAG" CHAR(1) NOT NULL, 
		"CANCEL_FLAG" CHAR(1) NOT NULL, 
		"PARTS_PROP_REV_NO" CHAR(3) NOT NULL, 
		"TMP_ABOLISH_DATE" DATE NOT NULL, 
		"TMP_CANCEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004002" (
		"SUB_PARTS_NO" CHAR(15) NOT NULL, 
		"PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"PS_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PS_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PS_STATUS" CHAR(2) NOT NULL, 
		"APPROVED_DATE" DATE NOT NULL, 
		"APPROVER_USER_ID" CHAR(10) NOT NULL, 
		"EDITOR_USER_ID" CHAR(10) NOT NULL, 
		"ADOPT_DATE" DATE NOT NULL, 
		"ABOLISH_DATE" DATE NOT NULL, 
		"TMP_REGIST_DATE" DATE NOT NULL, 
		"PENDING_DECIDED_DATE" DATE NOT NULL, 
		"CONSUMPTION_ROUTING" CHAR(2) NOT NULL, 
		"PROCESSING_CODE" CHAR(1) NOT NULL, 
		"MANAGEMENT_STATUS" CHAR(1) NOT NULL, 
		"SUPPLY_CODE" CHAR(1) NOT NULL, 
		"SHIP_SUPPLY_CLASS" CHAR(1) NOT NULL, 
		"ADOPT_CHECK_CODE" CHAR(1) NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"DATA_CHECK_RESULT" CHAR(1) NOT NULL, 
		"REPR_OF_MAIN_ECS_NO" CHAR(11) NOT NULL, 
		"SKIP_FLAG" CHAR(1) NOT NULL, 
		"CANCEL_FLAG" CHAR(1) NOT NULL, 
		"ENGINEERING_PS_REV_NO" CHAR(3) NOT NULL, 
		"TMP_ABOLISH_DATE" DATE NOT NULL, 
		"TMP_CANCEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004003" (
		"SEQUENCING_NO" CHAR(2) NOT NULL, 
		"SEQUENCING_NAME" VARCHAR(100) NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004004" (
		"MAPPING_NO" CHAR(4) NOT NULL, 
		"NEW_CONS_ROUT_NO" CHAR(2) NOT NULL, 
		"NEW_JOB_SEQ_NO" CHAR(2) NOT NULL, 
		"NEW_UNIT_CLASS" CHAR(1) NOT NULL, 
		"SUPPLIER_CODE_COND" VARCHAR(20) NOT NULL, 
		"NEW_SUPPLY_CODE" CHAR(1) NOT NULL, 
		"NEW_PROCESSING_CODE" CHAR(1) NOT NULL, 
		"PRCSSING_CODE_FOR_CHK" CHAR(1) NOT NULL, 
		"SEPICS_CONS_ROUT_NO" CHAR(4) NOT NULL, 
		"SEPICS_RCV_ROUT_NO" CHAR(4) NOT NULL, 
		"SEPICS_JOB_SEQ_NO" CHAR(4) NOT NULL, 
		"SEPICS_UNIT_CLASS" CHAR(1) NOT NULL, 
		"SEPICS_SUPPLY_CODE" CHAR(1) NOT NULL, 
		"SEPICS_PROCESSING_CODE" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004005" (
		"PROCESSING_CODE" CHAR(1) NOT NULL, 
		"CONTENTS" VARCHAR(100) NOT NULL, 
		"ORDER_MOVE_DIV" CHAR(1) NOT NULL, 
		"INTER_EXTER_CLASS" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004006" (
		"BATCH_UNIQUE_KEY" VARCHAR(40) NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PN_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PN_REV_NO" CHAR(3) NOT NULL, 
		"ERROR_GROUP_NO" SMALLINT NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004007" (
		"BATCH_UNIQUE_KEY" VARCHAR(40) NOT NULL, 
		"SEAQUENCE" SMALLINT NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PN_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PN_REV_NO" CHAR(3) NOT NULL, 
		"SUB_PARTS_NO" CHAR(15) NOT NULL, 
		"PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"PS_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PS_REV_NO" CHAR(3) NOT NULL, 
		"REPR_OF_MAIN_ECS_NO" CHAR(11) NOT NULL, 
		"ERROR_MESSAGE" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "TB004001" ADD CONSTRAINT "TB004001_PK" PRIMARY KEY
	("PARTS_NO", 
	 "ENGINEERING_PN_REV_NO", 
	 "FACTORY_PN_REV_NO");

ALTER TABLE "TB004002" ADD CONSTRAINT "TB004002_PK" PRIMARY KEY
	("SUB_PARTS_NO", 
	 "PARENT_PARTS_NO", 
	 "PS_REV_NO", 
	 "FACTORY_PS_REV_NO");

ALTER TABLE "TB004003" ADD CONSTRAINT "TB004003_PK" PRIMARY KEY
	("SEQUENCING_NO");

ALTER TABLE "TB004004" ADD CONSTRAINT "TB004004_PK" PRIMARY KEY
	("MAPPING_NO");

ALTER TABLE "TB004005" ADD CONSTRAINT "TB004005_PK" PRIMARY KEY
	("PROCESSING_CODE");

ALTER TABLE "TB004006" ADD CONSTRAINT "TB004006_PK" PRIMARY KEY
	("BATCH_UNIQUE_KEY", 
	 "PARTS_NO", 
	 "ENGINEERING_PN_REV_NO", 
	 "FACTORY_PN_REV_NO");

ALTER TABLE "TB004007" ADD CONSTRAINT "TB004007_PK" PRIMARY KEY
	("BATCH_UNIQUE_KEY", 
	 "SEAQUENCE");

