--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "TB008001" (
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"FINAL_OVER" CHAR(1) NOT NULL, 
		"REPR_SERIES_CLASS" CHAR(3) NOT NULL, 
		"SERIES_CLASS_DIFF" CHAR(1) NOT NULL, 
		"STRUCT_BLK_REGIST_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008002" (
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"FINAL_OVER" CHAR(1) NOT NULL, 
		"COMBINED_INDEX" CHAR(30) NOT NULL, 
		"KIND" CHAR(1) NOT NULL, 
		"FACTORY_NEW_KEY" CHAR(2) NOT NULL, 
		"STRUCTURE_REV_NO" CHAR(2) NOT NULL, 
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_LEVEL" CHAR(1) NOT NULL, 
		"REFERENCE" CHAR(1) NOT NULL, 
		"SERIES_CLASS" CHAR(3) NOT NULL, 
		"ECS_NO_NOW" CHAR(5) NOT NULL, 
		"DWG_NO_FOR_PARTS" CHAR(15) NOT NULL, 
		"BLOCK_ITEM" CHAR(40) NOT NULL, 
		"SUPPLMENTARY_CLASS" CHAR(1) NOT NULL, 
		"CAL_CODE" CHAR(2) NOT NULL, 
		"REVISION_NO" CHAR(2) NOT NULL, 
		"DRAWING_CODE" CHAR(1) NOT NULL, 
		"DRAWER" CHAR(1) NOT NULL, 
		"DWG_JDG_CODE" CHAR(1) NOT NULL, 
		"IMPORTANCE_SAFTY" CHAR(1) NOT NULL, 
		"CONSPUMTION_ROUTING" CHAR(4) NOT NULL, 
		"RECEIVE_DELIVER_SEQ" CHAR(4) NOT NULL, 
		"JOB_SEQUENCING" CHAR(4) NOT NULL, 
		"DESIGN_PER_CAR_QTY" CHAR(4) NOT NULL, 
		"FACTORY_PER_CAR_QTY" CHAR(4) NOT NULL, 
		"DWG_NO_FOR_SUB_PARTS" CHAR(15) NOT NULL, 
		"OVER_FOR_SUB_PARTS" CHAR(1) NOT NULL, 
		"INDEX_FOR_SUB_PARTS" CHAR(2) NOT NULL, 
		"KIND_FOR_SUB_PARTS" CHAR(1) NOT NULL, 
		"SYMBOL" CHAR(1) NOT NULL, 
		"STURCT_REGIST_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008003" (
		"LIST_CODE" CHAR(4) NOT NULL, 
		"MASSPRO_TRIAL_DIV" CHAR(1) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"DESIGNER" CHAR(11) NOT NULL, 
		"PHONE_NUMBER" CHAR(4) NOT NULL, 
		"AL_BLK_ECS_NO_NOW" CHAR(5) NOT NULL, 
		"AL_BLOCK_SYMBOL" CHAR(1) NOT NULL, 
		"DELETE_FLAG" CHAR(1) NOT NULL, 
		"AL_BLOCK_REGIST_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008004" (
		"LIST_CODE" CHAR(4) NOT NULL, 
		"MASSPRO_TRIAL_DIV" CHAR(1) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"FINAL_PARTS_NO" CHAR(15) NOT NULL, 
		"AL_REV_NO" CHAR(2) NOT NULL, 
		"SPEC_CLASS" CHAR(1) NOT NULL, 
		"PARALLEL_SEQUENCING" CHAR(1) NOT NULL, 
		"APPLY_CLASS" CHAR(1) NOT NULL, 
		"COLOR" CHAR(5) NOT NULL, 
		"DESTINATION_1" CHAR(2) NOT NULL, 
		"DESTINATION_2" CHAR(2) NOT NULL, 
		"DESTINATION_3" CHAR(2) NOT NULL, 
		"DESTINATION_4" CHAR(2) NOT NULL, 
		"DESTINATION_5" CHAR(2) NOT NULL, 
		"OPTION_1" CHAR(5) NOT NULL, 
		"OPTION_2" CHAR(5) NOT NULL, 
		"OPTION_3" CHAR(5) NOT NULL, 
		"OPTION_4" CHAR(5) NOT NULL, 
		"AL_ADOPT_DATE" DATE NOT NULL, 
		"AL_ABOLISH_DATE" DATE NOT NULL, 
		"APPLIED_NO" CHAR(95) NOT NULL, 
		"APP_MDL_ECS_NO_NOW" CHAR(5) NOT NULL, 
		"DESIGN_MEMO" CHAR(10) NOT NULL, 
		"FACTORY_MEMO" CHAR(20) NOT NULL, 
		"KEY1_FINAL_PARTS_NO" CHAR(15) NOT NULL, 
		"SERIES_CLASS" CHAR(3) NOT NULL, 
		"FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"KEY3_LIST_CODE" CHAR(4) NOT NULL, 
		"KEY3_MASSPRO_TRIAL_DIV" CHAR(1) NOT NULL, 
		"KEY3_BLOCK_NO" CHAR(4) NOT NULL, 
		"KEY3_REPR_SERIES_CLASS" CHAR(3) NOT NULL, 
		"KEY3_SERIES_CLASS_DIFF" CHAR(1) NOT NULL, 
		"KEY3_OVER" CHAR(1) NOT NULL, 
		"KEY3_COLUMN" CHAR(1) NOT NULL, 
		"KEY3_COLOR_DIFF" CHAR(2) NOT NULL, 
		"KEY4_LIST_CODE" CHAR(4) NOT NULL, 
		"KEY4_MASSPRO_TRIAL_DIV" CHAR(1) NOT NULL, 
		"KEY4_BLOCK_NO" CHAR(4) NOT NULL, 
		"KEY2_REPR_SERIES_CLASS" CHAR(3) NOT NULL, 
		"KEY2_SERIES_CLASS_DIFF" CHAR(1) NOT NULL, 
		"KEY2_OVER" CHAR(1) NOT NULL, 
		"KEY2_COLUMN" CHAR(1) NOT NULL, 
		"KEY2_FINAL_PARTS_NO" CHAR(15) NOT NULL, 
		"KEY2_SPEC_CLASS" CHAR(1) NOT NULL, 
		"KEY2_PARALLEL_SEQUENCING" CHAR(1) NOT NULL, 
		"KEY2_AL_REV_NO" CHAR(2) NOT NULL, 
		"EXPLODE_SIGN" CHAR(1) NOT NULL, 
		"DELETE_FLAG" CHAR(1) NOT NULL, 
		"SYMBOL" CHAR(1) NOT NULL, 
		"APP_MDL_REGIST_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008005" (
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"FINAL_OVER" CHAR(1) NOT NULL, 
		"COMBINED_INDEX" CHAR(30) NOT NULL, 
		"KIND" CHAR(1) NOT NULL, 
		"FACTORY_NEW_KEY" CHAR(2) NOT NULL, 
		"STRUCTURE_REV_NO" CHAR(2) NOT NULL, 
		"FACTORY_SERIES" CHAR(4) NOT NULL, 
		"DEMANDER" CHAR(1) NOT NULL, 
		"KEY1_FACTORY_SERIES" CHAR(4) NOT NULL, 
		"KEY1_BLOCK_NO" CHAR(4) NOT NULL, 
		"KEY1_REPR_SERIES_CLASS" CHAR(3) NOT NULL, 
		"KEY1_SERIES_CLASS_DIFF" CHAR(1) NOT NULL, 
		"KEY1_FINAL_OVER" CHAR(1) NOT NULL, 
		"KEY1_LINE_NO" CHAR(5) NOT NULL, 
		"COLOR_GEN_SIGN" CHAR(1) NOT NULL, 
		"FACT_SERIES_REGIST_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008006" (
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"FINAL_OVER" CHAR(1) NOT NULL, 
		"COMBINED_INDEX" CHAR(30) NOT NULL, 
		"KIND" CHAR(1) NOT NULL, 
		"FACTORY_NEW_KEY" CHAR(2) NOT NULL, 
		"STRUCTURE_REV_NO" CHAR(2) NOT NULL, 
		"FACTORY_SERIES" CHAR(4) NOT NULL, 
		"COLOR_DIFF" CHAR(2) NOT NULL, 
		"PL_REV_NO" CHAR(2) NOT NULL, 
		"PARALLEL_SEQUENCING" CHAR(1) NOT NULL, 
		"MASSPRO_KD_CLASS" CHAR(2) NOT NULL, 
		"CONSUMPTION_ROUTING" CHAR(4) NOT NULL, 
		"RECEIVE_DELIVER_SEQ" CHAR(4) NOT NULL, 
		"JOB_SEQUENCING" CHAR(4) NOT NULL, 
		"BASE_PROD" CHAR(2) NOT NULL, 
		"PROCESSING_CODE" CHAR(1) NOT NULL, 
		"MANAGEMENT_STATUS" CHAR(1) NOT NULL, 
		"PL_ADOPT_DATE" DATE NOT NULL, 
		"PL_ABOLISH_DATE" DATE NOT NULL, 
		"SUPPLY_CODE" CHAR(1) NOT NULL, 
		"SHIP_SUPPLY_CLASS" CHAR(1) NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"ADOPT_CHECK_CODE" CHAR(1) NOT NULL, 
		"ARRANGE_CLASS" CHAR(1) NOT NULL, 
		"PARTS_GROUP" CHAR(2) NOT NULL, 
		"PARTS_ID" CHAR(4) NOT NULL, 
		"BLOCK_ITEM" CHAR(40) NOT NULL, 
		"INT_EXT_DIV" CHAR(1) NOT NULL, 
		"SUPPLY_SECTION_1" CHAR(5) NOT NULL, 
		"SUPPLY_SECTION_2" CHAR(5) NOT NULL, 
		"SUPPLY_SECTION_3" CHAR(5) NOT NULL, 
		"SUPPLY_SECTION_4" CHAR(5) NOT NULL, 
		"LINE_CLASS_1" CHAR(1) NOT NULL, 
		"LINE_CLASS_2" CHAR(1) NOT NULL, 
		"LINE_CLASS_3" CHAR(1) NOT NULL, 
		"LINE_CLASS_4" CHAR(1) NOT NULL, 
		"PROD_LINE_CLASS_1" CHAR(1) NOT NULL, 
		"PROD_LINE_CLASS_2" CHAR(1) NOT NULL, 
		"PROD_LINE_CLASS_3" CHAR(1) NOT NULL, 
		"PROD_LINE_CLASS_4" CHAR(1) NOT NULL, 
		"KEY2_ECS_NO_NOW" CHAR(5) NOT NULL, 
		"KEY2_FACTORY_SERIES" CHAR(4) NOT NULL, 
		"KEY2_BLOCK_NO" CHAR(4) NOT NULL, 
		"KEY2_FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"KEY2_FINAL_OVER" CHAR(1) NOT NULL, 
		"KEY2_COMBINED_INDEX" CHAR(30) NOT NULL, 
		"KEY2_KIND" CHAR(1) NOT NULL, 
		"KEY2_FACTORY_NEW_KEY" CHAR(2) NOT NULL, 
		"KEY2_STRUCTURE_REV_NO" CHAR(2) NOT NULL, 
		"KEY2_COLOR_DIFF" CHAR(2) NOT NULL, 
		"KEY2_PL_REV_NO" CHAR(2) NOT NULL, 
		"KEY2_PARALLEL_SEQUENCING" CHAR(1) NOT NULL, 
		"KEY2_MASSPRO_KD_CLASS" CHAR(2) NOT NULL, 
		"PL_PLAN_COLOR_GEN_SIGN" CHAR(1) NOT NULL, 
		"AUTOMATIC_ID" CHAR(1) NOT NULL, 
		"CARRY_FORWARD_NUM" CHAR(1) NOT NULL, 
		"PL_PLAN_SYMBOL" CHAR(1) NOT NULL, 
		"PL_PLAN_REGIST_DATE" DATE NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008007" (
		"BATCH_ID" CHAR(10) NOT NULL, 
		"SEND_HOST" CHAR(8) NOT NULL, 
		"RECEIVE_HOST" CHAR(8) NOT NULL, 
		"OPERATION_TYPE" CHAR(1) NOT NULL, 
		"DATA_KIND" CHAR(8) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"RECORD_NUMBER" CHAR(7) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "TB008001" ADD CONSTRAINT "TB008001_PK" PRIMARY KEY
	("BLOCK_NO", 
	 "FINAL_TITLE_DWG_NO", 
	 "FINAL_OVER");

ALTER TABLE "TB008002" ADD CONSTRAINT "TB008002_PK" PRIMARY KEY
	("BLOCK_NO", 
	 "FINAL_TITLE_DWG_NO", 
	 "FINAL_OVER", 
	 "COMBINED_INDEX", 
	 "KIND", 
	 "FACTORY_NEW_KEY", 
	 "STRUCTURE_REV_NO");

ALTER TABLE "TB008003" ADD CONSTRAINT "TB008003_PK" PRIMARY KEY
	("LIST_CODE", 
	 "MASSPRO_TRIAL_DIV", 
	 "BLOCK_NO");

ALTER TABLE "TB008004" ADD CONSTRAINT "TB008004_PK" PRIMARY KEY
	("LIST_CODE", 
	 "MASSPRO_TRIAL_DIV", 
	 "BLOCK_NO", 
	 "FINAL_PARTS_NO", 
	 "AL_REV_NO", 
	 "SPEC_CLASS", 
	 "PARALLEL_SEQUENCING");

ALTER TABLE "TB008005" ADD CONSTRAINT "TB008005_PK" PRIMARY KEY
	("BLOCK_NO", 
	 "FINAL_TITLE_DWG_NO", 
	 "FINAL_OVER", 
	 "COMBINED_INDEX", 
	 "KIND", 
	 "FACTORY_NEW_KEY", 
	 "STRUCTURE_REV_NO", 
	 "FACTORY_SERIES");

ALTER TABLE "TB008006" ADD CONSTRAINT "TB008006_PK" PRIMARY KEY
	("BLOCK_NO", 
	 "FINAL_TITLE_DWG_NO", 
	 "FINAL_OVER", 
	 "COMBINED_INDEX", 
	 "KIND", 
	 "FACTORY_NEW_KEY", 
	 "STRUCTURE_REV_NO", 
	 "FACTORY_SERIES", 
	 "COLOR_DIFF", 
	 "PL_REV_NO", 
	 "PARALLEL_SEQUENCING", 
	 "MASSPRO_KD_CLASS");

ALTER TABLE "TB008007" ADD CONSTRAINT "TB008007_PK" PRIMARY KEY
	("BATCH_ID");

