--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "TB011001" (
		"ORGANIZATION_CODE" CHAR(6) NOT NULL, 
		"DEPARTMENT_CODE" CHAR(2) NOT NULL, 
		"DEPARTMENT_NAME" VARCHAR(60) NOT NULL, 
		"SECTION_CODE" CHAR(2) NOT NULL, 
		"SECTION_NAME" VARCHAR(60) NOT NULL, 
		"TEAM_CODE" CHAR(2) NOT NULL, 
		"TEAM_NAME" VARCHAR(60) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011002" (
		"USER_ID" CHAR(10) NOT NULL, 
		"EMPLOYEE_NO" CHAR(8) NOT NULL, 
		"KANJI_NAME" VARCHAR(30) NOT NULL, 
		"ROMAN_NAME" VARCHAR(60) NOT NULL, 
		"KANA_NAME" VARCHAR(60) NOT NULL, 
		"ORGANIZATION_CODE" CHAR(6) NOT NULL, 
		"E_MAIL_ADDRESS" VARCHAR(256) NOT NULL, 
		"PHONE_NO" CHAR(15) NOT NULL, 
		"LANGUAGE_CODE" CHAR(2) NOT NULL, 
		"ROLE_ID" CHAR(10) NOT NULL, 
		"AUTO_DEL_EXCEPT_FLAG" CHAR(6) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATE_UPDATE_DATE" DATE NOT NULL, 
		"AUTH_STOP_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"SESSION_ID" VARCHAR(104) NOT NULL, 
		"LOGIN_TIME" TIMESTAMP NOT NULL, 
		"LOGOUT_TIME" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011003" (
		"ROLE_ID" CHAR(10) NOT NULL, 
		"ROLE_NAME" VARCHAR(100) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011004" (
		"DOMAIN_ID" CHAR(10) NOT NULL, 
		"DOMAIN_NAME" VARCHAR(120) NOT NULL, 
		"DOMAIN_ORDER" SMALLINT NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011005" (
		"SCREEN_ID" CHAR(10) NOT NULL, 
		"SCREEN_NAME" VARCHAR(120) NOT NULL, 
		"DOMAIN_ID" CHAR(10) NOT NULL, 
		"MENU_DISPLAY_FLAG" CHAR(1) NOT NULL, 
		"SCREEN_ORDER" SMALLINT NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011006" (
		"ROLE_ID" CHAR(10) NOT NULL, 
		"SCREEN_ID" CHAR(10) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011007" (
		"SCREEN_EVENT_ID" CHAR(10) NOT NULL, 
		"SCREEN_ID" CHAR(10) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011008" (
		"ROLE_ID" CHAR(10) NOT NULL, 
		"SCREEN_EVENT_ID" CHAR(10) NOT NULL, 
		"AUTH_CONTROL_KIND" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011009" (
		"ROLE_ID" CHAR(10) NOT NULL, 
		"SCREEN_ID" CHAR(10) NOT NULL, 
		"SCREEN_ITEM_ID" CHAR(30) NOT NULL, 
		"AUTH_CONTROL_KIND" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011010" (
		"BATCH_ID" CHAR(10) NOT NULL, 
		"BATCH_NAME" VARCHAR(100) NOT NULL, 
		"PATH" VARCHAR(256) NOT NULL, 
		"EXCLUSIVE_BATCH_ID" VARCHAR(100) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011011" (
		"BATCH_SEQ" CHAR(30) NOT NULL, 
		"BATCH_ID" CHAR(10) NOT NULL, 
		"BATCH_PARAMETER" VARCHAR(1000) NOT NULL, 
		"BATCH_STATUS" CHAR(1) NOT NULL, 
		"BATCH_REQUEST_TIME" TIMESTAMP NOT NULL, 
		"BATCH_START_TIME" TIMESTAMP NOT NULL, 
		"BATCH_END_TIME" TIMESTAMP NOT NULL, 
		"REQUEST_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011012" (
		"MAIL_SEND_CONTROL_NO" CHAR(30) NOT NULL, 
		"MAIL_TEMPLATE_ID" CHAR(10) NOT NULL, 
		"SENDER_MAIL_ADDRESS" VARCHAR(256) NOT NULL, 
		"MAIL_SEND_STATUS" CHAR(1) NOT NULL, 
		"MAIL_SEND_MODE" CHAR(1) NOT NULL, 
		"MAIL_REGISTER_TIME" TIMESTAMP NOT NULL, 
		"MAIL_SEND_TIME" TIMESTAMP NOT NULL, 
		"MAIL_SUBJECT" VARCHAR(600) NOT NULL, 
		"MAIL_BODY" CLOB(2000000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011013" (
		"MAIL_SEND_CONTROL_NO" CHAR(30) NOT NULL, 
		"ADDRESS_KIND" CHAR(1) NOT NULL, 
		"SENDER_NO" SMALLINT NOT NULL, 
		"RECEIVER_MAIL_ADDRESS" VARCHAR(256) NOT NULL, 
		"MAIL_SEND_STATUS" CHAR(1) NOT NULL, 
		"MAIL_SEND_TIME" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011014" (
		"APPLICATION_NO" CHAR(10) NOT NULL, 
		"KEY_1" CHAR(15) NOT NULL, 
		"KEY_2" CHAR(15) NOT NULL, 
		"KEY_3" CHAR(15) NOT NULL, 
		"KEY_4" CHAR(15) NOT NULL, 
		"KEY_5" CHAR(15) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011015" (
		"CODE_GROUP_ID" CHAR(10) NOT NULL, 
		"CODE_VALUE" CHAR(10) NOT NULL, 
		"JP_DISPLAY_NAME" VARCHAR(300) NOT NULL, 
		"EN_DISPLAY_NAME" VARCHAR(100) NOT NULL, 
		"CODE_GROUP_CLASS" CHAR(1) NOT NULL, 
		"CODE_GROUP_DESCRIPTION" VARCHAR(600) NOT NULL, 
		"CODE_VALUE_DESCRIPTION" VARCHAR(600) NOT NULL, 
		"CODE_VALUE_NAME" VARCHAR(100) NOT NULL, 
		"CODE_ORDER" SMALLINT NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "TB011001" ADD CONSTRAINT "TB011001_PK" PRIMARY KEY
	("ORGANIZATION_CODE");

ALTER TABLE "TB011002" ADD CONSTRAINT "TB011002_PK" PRIMARY KEY
	("USER_ID");

ALTER TABLE "TB011003" ADD CONSTRAINT "TB011003_PK" PRIMARY KEY
	("ROLE_ID");

ALTER TABLE "TB011004" ADD CONSTRAINT "TB011004_PK" PRIMARY KEY
	("DOMAIN_ID");

ALTER TABLE "TB011005" ADD CONSTRAINT "TB011005_PK" PRIMARY KEY
	("SCREEN_ID");

ALTER TABLE "TB011006" ADD CONSTRAINT "TB011006_PK" PRIMARY KEY
	("ROLE_ID", 
	 "SCREEN_ID");

ALTER TABLE "TB011007" ADD CONSTRAINT "TB011007_PK" PRIMARY KEY
	("SCREEN_EVENT_ID");

ALTER TABLE "TB011008" ADD CONSTRAINT "TB011008_PK" PRIMARY KEY
	("ROLE_ID", 
	 "SCREEN_EVENT_ID");

ALTER TABLE "TB011009" ADD CONSTRAINT "TB011009_PK" PRIMARY KEY
	("ROLE_ID", 
	 "SCREEN_ID", 
	 "SCREEN_ITEM_ID");

ALTER TABLE "TB011010" ADD CONSTRAINT "TB011010_PK" PRIMARY KEY
	("BATCH_ID");

ALTER TABLE "TB011011" ADD CONSTRAINT "TB011011_PK" PRIMARY KEY
	("BATCH_SEQ");

ALTER TABLE "TB011012" ADD CONSTRAINT "TB011012_PK" PRIMARY KEY
	("MAIL_SEND_CONTROL_NO");

ALTER TABLE "TB011013" ADD CONSTRAINT "TB011013_PK" PRIMARY KEY
	("MAIL_SEND_CONTROL_NO", 
	 "ADDRESS_KIND", 
	 "SENDER_NO");

ALTER TABLE "TB011014" ADD CONSTRAINT "TB011014_PK" PRIMARY KEY
	("APPLICATION_NO");

ALTER TABLE "TB011015" ADD CONSTRAINT "TB011015_PK" PRIMARY KEY
	("CODE_GROUP_ID", 
	 "CODE_VALUE");

