-- 設通進捗ステータス別の設通番号と設通改訂番号を取得するVIEW
CREATE VIEW VW005001 (
	KIND,				--設通進捗ステータスの種類
	ECS_NO,				--設通番号
	ECS_REV_NO,			--設通改訂番号
	REPR_SIMUL_CLASS,	--代表・同指示区分
	ECS_SERIES,			--設通シリーズ
	SECTION_CODE,		--課コード
	RECEIVED_DATE		--設通受領日
)
AS (
-- 未設審の設通を取得（KIND=1）
SELECT
	'1' AS KIND,
	A.ECS_NO,
	A.ECS_REV_NO,
	A.REPR_SIMUL_CLASS,
	A.ECS_SERIES,
	A.SECTION_CODE,
	A.RECEIVED_DATE
FROM
	TB003001 A
WHERE
	A.ECS_REV_NO = (SELECT MAX(ECS_REV_NO) FROM TB003001 B WHERE A.ECS_NO = B.ECS_NO)
AND ( NOT EXISTS (SELECT ECS_NO FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO)
  OR (SELECT MIN(ECS_MEETING_DATE) FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO) > SYSDATE)
UNION
-- 設審済みの設通を取得（KIND=2）
SELECT
	'2' AS KIND,
	A.ECS_NO,
	A.ECS_REV_NO,
	A.REPR_SIMUL_CLASS,
	A.ECS_SERIES,
	A.SECTION_CODE,
	A.RECEIVED_DATE
FROM
	TB003001 A
WHERE
	A.ECS_REV_NO = (SELECT MAX(ECS_REV_NO) FROM TB003001 B WHERE A.ECS_NO = B.ECS_NO)
AND (SELECT MIN(ECS_MEETING_DATE) FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO) < SYSDATE
UNION
-- 設審済み未発行の設通を取得（KIND=3）
SELECT
	'3' AS KIND,
	A.ECS_NO,
	A.ECS_REV_NO,
	A.REPR_SIMUL_CLASS,
	A.ECS_SERIES,
	A.SECTION_CODE,
	A.RECEIVED_DATE
FROM
	TB003001 A
WHERE
	A.ECS_REV_NO = (SELECT MAX(ECS_REV_NO) FROM TB003001 B WHERE A.ECS_NO = B.ECS_NO)
AND (SELECT MIN(ECS_MEETING_DATE) FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO) < SYSDATE
AND NOT EXISTS (SELECT D.ECS_ISSUE_DATE FROM TB003009 D WHERE A.ECS_NO = D.ECS_NO AND A.ECS_REV_NO = D.ECS_REV_NO)
UNION
-- 設審済み発行済み設通を取得（KIND=4）
SELECT
	'4' AS KIND,
	A.ECS_NO,
	A.ECS_REV_NO,
	A.REPR_SIMUL_CLASS,
	A.ECS_SERIES,
	A.SECTION_CODE,
	A.RECEIVED_DATE
FROM
	TB003001 A
WHERE
	A.ECS_REV_NO = (SELECT MAX(ECS_REV_NO) FROM TB003001 B WHERE A.ECS_NO = B.ECS_NO)
AND (SELECT MIN(ECS_MEETING_DATE) FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO) < SYSDATE
AND EXISTS (SELECT D.ECS_ISSUE_DATE FROM TB003009 D WHERE A.ECS_NO = D.ECS_NO AND A.ECS_REV_NO = D.ECS_REV_NO)
UNION
-- 設審済みダミー発行設通を取得（KIND=99）
SELECT
	'99' AS KIND,
	A.ECS_NO,
	A.ECS_REV_NO,
	A.REPR_SIMUL_CLASS,
	A.ECS_SERIES,
	A.SECTION_CODE,
	A.RECEIVED_DATE
FROM
	TB003001 A
WHERE
	A.ECS_REV_NO = (SELECT MAX(ECS_REV_NO) FROM TB003001 B WHERE A.ECS_NO = B.ECS_NO)
AND (SELECT MIN(ECS_MEETING_DATE) FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO) < SYSDATE
AND
 EXISTS
 (SELECT D.ECS_ISSUE_DATE FROM TB003009 D
  WHERE A.ECS_NO = D.ECS_NO
    AND A.ECS_REV_NO = D.ECS_REV_NO
    AND D.ECS_ISSUE_REV_NO = (SELECT MAX(ECS_ISSUE_REV_NO) FROM TB003009 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.DUMMY_ISSUE_FLAG = '1')
UNION
-- 設審済み未決（全体）の代表設通を取得（KIND=5）
SELECT
	'5' AS KIND,
	A.ECS_NO,
	A.ECS_REV_NO,
	A.REPR_SIMUL_CLASS,
	A.ECS_SERIES,
	A.SECTION_CODE,
	A.RECEIVED_DATE
FROM
	TB003001 A
WHERE
	A.ECS_REV_NO = (SELECT MAX(ECS_REV_NO) FROM TB003001 B WHERE A.ECS_NO = B.ECS_NO)
AND (SELECT MIN(ECS_MEETING_DATE) FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO) < SYSDATE
AND
EXISTS
(
	SELECT COUNT(DISTINCT IMPLEMENT_EVENT_ID) 
	FROM TB003008 D
	WHERE D.ECS_NO = A.ECS_NO AND D.ECS_REV_NO = A.ECS_REV_NO AND
	EXISTS(SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE E.ECS_NO = D.ECS_NO AND E.ECS_REV_NO = D.ECS_REV_NO
			GROUP BY E.ECS_NO,E.ECS_REV_NO HAVING D.IMPL_DATE_INPUT_COL=MIN(E.IMPL_DATE_INPUT_COL)) AND
	EXISTS(SELECT MAX(F.ECS_IMPL_REV_NO) FROM TB003008 F WHERE F.ECS_NO = D.ECS_NO AND F.ECS_REV_NO = D.ECS_REV_NO
			GROUP BY F.ECS_NO,F.ECS_REV_NO HAVING D.ECS_IMPL_REV_NO=MAX(F.ECS_IMPL_REV_NO))
	GROUP BY D.ECS_NO,D.ECS_REV_NO
	HAVING COUNT(DISTINCT IMPLEMENT_EVENT_ID)=1
)
AND
 (SELECT COUNT(D.IMPLEMENT_EVENT_ID) FROM TB003008 D
  WHERE A.ECS_NO = D.ECS_NO AND A.ECS_REV_NO = D.ECS_REV_NO
    AND D.IMPL_DATE_INPUT_COL = (SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.ECS_IMPL_REV_NO = (SELECT MAX(E.ECS_IMPL_REV_NO) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.IMPLEMENT_EVENT_ID = '9999'
  GROUP BY D.ECS_NO,D.ECS_REV_NO,D.ECS_IMPL_REV_NO) >= 1
AND A.REPR_SIMUL_CLASS = '0'
UNION
-- 設審済み未決（全体）の同指示設通を取得（KIND=5）
SELECT
	'5' AS KIND,
	A.ECS_NO,
	A.ECS_REV_NO,
	A.REPR_SIMUL_CLASS,
	A.ECS_SERIES,
	A.SECTION_CODE,
	A.RECEIVED_DATE
FROM
	TB003001 A
INNER JOIN
	TB003002 H
 ON A.ECS_NO = H.SIMULTANEOUS_ECS_NO
AND H.REPR_ECS_REV_NO = (SELECT MAX(REPR_ECS_REV_NO) FROM TB003002 I WHERE A.ECS_NO = I.SIMULTANEOUS_ECS_NO)
WHERE
	A.ECS_REV_NO = (SELECT MAX(ECS_REV_NO) FROM TB003001 B WHERE A.ECS_NO = B.ECS_NO)
AND (SELECT MIN(ECS_MEETING_DATE) FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO) > SYSDATE
AND
EXISTS
(
	SELECT COUNT(DISTINCT IMPLEMENT_EVENT_ID) 
	FROM TB003008 D
	WHERE D.ECS_NO = A.ECS_NO AND D.ECS_REV_NO = A.ECS_REV_NO AND
	EXISTS(SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE E.ECS_NO = D.ECS_NO AND E.ECS_REV_NO = D.ECS_REV_NO
			GROUP BY E.ECS_NO,E.ECS_REV_NO HAVING D.IMPL_DATE_INPUT_COL=MIN(E.IMPL_DATE_INPUT_COL)) AND
	EXISTS(SELECT MAX(F.ECS_IMPL_REV_NO) FROM TB003008 F WHERE F.ECS_NO = D.ECS_NO AND F.ECS_REV_NO = D.ECS_REV_NO
			GROUP BY F.ECS_NO,F.ECS_REV_NO HAVING D.ECS_IMPL_REV_NO=MAX(F.ECS_IMPL_REV_NO))
	GROUP BY D.ECS_NO,D.ECS_REV_NO
	HAVING COUNT(DISTINCT IMPLEMENT_EVENT_ID)=1
)
AND
 (SELECT COUNT(D.IMPLEMENT_EVENT_ID) FROM TB003008 D
  WHERE H.REPR_ECS_NO = D.ECS_NO AND H.REPR_ECS_REV_NO = D.ECS_REV_NO
    AND D.IMPL_DATE_INPUT_COL = (SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.ECS_IMPL_REV_NO = (SELECT MAX(E.ECS_IMPL_REV_NO) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.IMPLEMENT_EVENT_ID = '9999'
  GROUP BY D.ECS_NO,D.ECS_REV_NO,D.ECS_IMPL_REV_NO) >= 1
AND A.REPR_SIMUL_CLASS = '1'
UNION
-- 設審済み未決（対象年改符号）の代表設通を取得（KIND=6）
SELECT
	'6' AS KIND,
	A.ECS_NO,
	A.ECS_REV_NO,
	A.REPR_SIMUL_CLASS,
	A.ECS_SERIES,
	A.SECTION_CODE,
	A.RECEIVED_DATE
FROM
	TB003001 A
WHERE
	A.ECS_REV_NO = (SELECT MAX(ECS_REV_NO) FROM TB003001 B WHERE A.ECS_NO = B.ECS_NO)
AND (SELECT MIN(ECS_MEETING_DATE) FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO) < SYSDATE
AND
EXISTS
(
	SELECT COUNT(DISTINCT IMPLEMENT_EVENT_ID) 
	FROM TB003008 D
	WHERE D.ECS_NO = A.ECS_NO AND D.ECS_REV_NO = A.ECS_REV_NO AND
	EXISTS(SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE E.ECS_NO = D.ECS_NO AND E.ECS_REV_NO = D.ECS_REV_NO
			GROUP BY E.ECS_NO,E.ECS_REV_NO HAVING D.IMPL_DATE_INPUT_COL=MIN(E.IMPL_DATE_INPUT_COL)) AND
	EXISTS(SELECT MAX(F.ECS_IMPL_REV_NO) FROM TB003008 F WHERE F.ECS_NO = D.ECS_NO AND F.ECS_REV_NO = D.ECS_REV_NO
			GROUP BY F.ECS_NO,F.ECS_REV_NO HAVING D.ECS_IMPL_REV_NO=MAX(F.ECS_IMPL_REV_NO))
	GROUP BY D.ECS_NO,D.ECS_REV_NO
	HAVING COUNT(DISTINCT IMPLEMENT_EVENT_ID) >= 2
)
AND
 (SELECT COUNT(D.IMPLEMENT_EVENT_ID) FROM TB003008 D
  WHERE A.ECS_NO = D.ECS_NO AND A.ECS_REV_NO = D.ECS_REV_NO
    AND D.IMPL_DATE_INPUT_COL = (SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.ECS_IMPL_REV_NO = (SELECT MAX(E.ECS_IMPL_REV_NO) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.IMPLEMENT_EVENT_ID = '9999'
  GROUP BY D.ECS_NO,D.ECS_REV_NO,D.ECS_IMPL_REV_NO) >= 1
AND A.REPR_SIMUL_CLASS = '0'
UNION
-- 設審済み未決（対象年改符号）の同指示設通を取得（KIND=6）
SELECT
	'6' as KIND,
	A.ECS_NO,
	A.ECS_REV_NO,
	A.REPR_SIMUL_CLASS,
	A.ECS_SERIES,
	A.SECTION_CODE,
	A.RECEIVED_DATE
FROM
	TB003001 A
INNER JOIN
	TB003002 H
 ON A.ECS_NO = H.SIMULTANEOUS_ECS_NO
AND H.REPR_ECS_REV_NO = (SELECT MAX(REPR_ECS_REV_NO) FROM TB003002 I WHERE A.ECS_NO = I.SIMULTANEOUS_ECS_NO)
WHERE
    A.ECS_REV_NO = (SELECT MAX(ECS_REV_NO) FROM TB003001 B WHERE A.ECS_NO = B.ECS_NO)
AND (SELECT MIN(ECS_MEETING_DATE) FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO) < SYSDATE
AND
EXISTS
(
	SELECT COUNT(DISTINCT IMPLEMENT_EVENT_ID) 
	FROM TB003008 D
	WHERE D.ECS_NO = A.ECS_NO AND D.ECS_REV_NO = A.ECS_REV_NO AND
	EXISTS(SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE E.ECS_NO = D.ECS_NO AND E.ECS_REV_NO = D.ECS_REV_NO
			GROUP BY E.ECS_NO,E.ECS_REV_NO HAVING D.IMPL_DATE_INPUT_COL=MIN(E.IMPL_DATE_INPUT_COL)) AND
	EXISTS(SELECT MAX(F.ECS_IMPL_REV_NO) FROM TB003008 F WHERE F.ECS_NO = D.ECS_NO AND F.ECS_REV_NO = D.ECS_REV_NO
			GROUP BY F.ECS_NO,F.ECS_REV_NO HAVING D.ECS_IMPL_REV_NO=MAX(F.ECS_IMPL_REV_NO))
	GROUP BY D.ECS_NO,D.ECS_REV_NO
	HAVING COUNT(DISTINCT IMPLEMENT_EVENT_ID) >= 2
)
AND
 (SELECT COUNT(D.IMPLEMENT_EVENT_ID) FROM TB003008 D
  WHERE H.REPR_ECS_NO = D.ECS_NO AND H.REPR_ECS_REV_NO = D.ECS_REV_NO
    AND D.IMPL_DATE_INPUT_COL = (SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.ECS_IMPL_REV_NO = (SELECT MAX(E.ECS_IMPL_REV_NO) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.IMPLEMENT_EVENT_ID = '9999'
  GROUP BY D.ECS_NO,D.ECS_REV_NO,D.ECS_IMPL_REV_NO) >= 1
AND A.REPR_SIMUL_CLASS = '1'
UNION
-- 設審済み未決（部品）の代表設通を取得（KIND=7）
SELECT
	'7' AS KIND,
	A.ECS_NO,
	A.ECS_REV_NO,
	A.REPR_SIMUL_CLASS,
	A.ECS_SERIES,
	A.SECTION_CODE,
	A.RECEIVED_DATE
FROM
	TB003001 A
WHERE
    A.ECS_REV_NO = (SELECT MAX(ECS_REV_NO) FROM TB003001 B WHERE A.ECS_NO = B.ECS_NO)
AND (SELECT MIN(ECS_MEETING_DATE) FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO) < SYSDATE
AND
 (SELECT COUNT(D.IMPLEMENT_EVENT_ID) FROM TB003008 D
  WHERE A.ECS_NO = D.ECS_NO AND A.ECS_REV_NO = D.ECS_REV_NO
    AND D.IMPL_DATE_INPUT_COL = (SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.ECS_IMPL_REV_NO = (SELECT MAX(E.ECS_IMPL_REV_NO) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.PARTIAL_PENDING_FLAG = '1'
  GROUP BY D.ECS_NO,D.ECS_REV_NO,D.ECS_IMPL_REV_NO) >= 1
AND
 (SELECT COUNT(D.IMPLEMENT_EVENT_ID) FROM TB003008 D
  WHERE A.ECS_NO = D.ECS_NO AND A.ECS_REV_NO = D.ECS_REV_NO
    AND D.IMPL_DATE_INPUT_COL = (SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.ECS_IMPL_REV_NO = (SELECT MAX(E.ECS_IMPL_REV_NO) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.IMPLEMENT_EVENT_ID = '9999'
  GROUP BY D.ECS_NO,D.ECS_REV_NO,D.ECS_IMPL_REV_NO) = 0
AND A.REPR_SIMUL_CLASS = '0'
UNION
-- 設審済み未決（部品）の同指示設通を取得（KIND=7）
SELECT
	'7' AS KIND,
	A.ECS_NO,
	A.ECS_REV_NO,
	A.REPR_SIMUL_CLASS,
	A.ECS_SERIES,
	A.SECTION_CODE,
	A.RECEIVED_DATE
FROM
	TB003001 A
INNER JOIN
	TB003002 H
 ON A.ECS_NO = H.SIMULTANEOUS_ECS_NO
AND H.REPR_ECS_REV_NO = (SELECT MAX(REPR_ECS_REV_NO) FROM TB003002 I WHERE A.ECS_NO = I.SIMULTANEOUS_ECS_NO)
WHERE
    A.ECS_REV_NO = (SELECT MAX(ECS_REV_NO) FROM TB003001 B WHERE A.ECS_NO = B.ECS_NO)
AND (SELECT MIN(ECS_MEETING_DATE) FROM TB003007 C WHERE A.ECS_NO = C.ECS_NO AND A.ECS_REV_NO = C.ECS_REV_NO) < SYSDATE
AND
 (SELECT COUNT(D.IMPLEMENT_EVENT_ID) FROM TB003008 D
  WHERE H.REPR_ECS_NO = D.ECS_NO AND H.REPR_ECS_REV_NO = D.ECS_REV_NO
    AND D.IMPL_DATE_INPUT_COL = (SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.ECS_IMPL_REV_NO = (SELECT MAX(E.ECS_IMPL_REV_NO) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.PARTIAL_PENDING_FLAG = '1'
  GROUP BY D.ECS_NO,D.ECS_REV_NO,D.ECS_IMPL_REV_NO) >= 1
AND
 (SELECT COUNT(D.IMPLEMENT_EVENT_ID) FROM TB003008 D
  WHERE H.REPR_ECS_NO = D.ECS_NO AND H.REPR_ECS_REV_NO = D.ECS_REV_NO
    AND D.IMPL_DATE_INPUT_COL = (SELECT MIN(E.IMPL_DATE_INPUT_COL) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.ECS_IMPL_REV_NO = (SELECT MAX(E.ECS_IMPL_REV_NO) FROM TB003008 E WHERE D.ECS_NO = E.ECS_NO AND D.ECS_REV_NO = E.ECS_REV_NO)
    AND D.IMPLEMENT_EVENT_ID = '9999'
  GROUP BY D.ECS_NO,D.ECS_REV_NO,D.ECS_IMPL_REV_NO) = 0
AND A.REPR_SIMUL_CLASS = '1');
