--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "TB002019" (
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PURCHASE_REV_NO" CHAR(3) NOT NULL, 
		"ARRANGEMENT_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002020" (
		"ECS_PROCESS_ID" CHAR(12) NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"ECS_REV_NO" CHAR(1) NOT NULL, 
		"PRECEDE_PROCESS_ID" VARCHAR(2000) NOT NULL, 
		"BATCH_REGISTRATION_STATUS" CHAR(1) NOT NULL, 
		"DATA_RECEIVE_STATUS" CHAR(1) NOT NULL, 
		"FACTORY_DATA_STATUS" CHAR(1) NOT NULL, 
		"REL_PARTS_DATA_STATUS" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003012" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"PROD_BASE_CODE" CHAR(1) NOT NULL, 
		"BODY_UNIT_DIV" CHAR(1) NOT NULL, 
		"EVENT_DATE" DATE NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009001" (
		"FMC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"FMC_DEV_MODEL_NAME" VARCHAR(100) NOT NULL, 
		"NEW_SYS_CONTROL_FLAG" CHAR(1) NOT NULL, 
		"BODY_UNIT_DIV" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "TB002019" ADD CONSTRAINT "TB002019_PK" PRIMARY KEY
	("DRAWING_NO", 
	 "DRAWING_REV_NO", 
	 "SUPPLIER_CODE", 
	 "PURCHASE_REV_NO");

ALTER TABLE "TB002020" ADD CONSTRAINT "TB002020_PK" PRIMARY KEY
	("ECS_PROCESS_ID");

ALTER TABLE "TB003012" ADD CONSTRAINT "TB003012_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "PROD_BASE_CODE");

ALTER TABLE "TB009001" ADD CONSTRAINT "TB009001_PK" PRIMARY KEY
	("FMC_DEV_MODEL_CODE");
