--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "TB001006" (
		"PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PN_REV_NO" CHAR(3) NOT NULL, 
		"PREV_PARTS_NO" CHAR(15) NOT NULL, 
		"PREV_DWG_NO" CHAR(15) NOT NULL, 
		"PREV_DWG_REV_NO" CHAR(2) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB001007" (
		"PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"SUB_PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PS_REV_NO" CHAR(3) NOT NULL, 
		"PREV_PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"PREV_SUB_PARTS_NO" CHAR(15) NOT NULL, 
		"PREV_DWG_NO" CHAR(15) NOT NULL, 
		"PREV_DWG_REV_NO" CHAR(2) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002020" (
		"ECS_PROCESS_ID" CHAR(12) NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"ECS_REV_NO" CHAR(1) NOT NULL, 
		"PRECEDE_PROCESS_ID" VARCHAR(2000) NOT NULL, 
		"BATCH_REGISTRATION_STATUS" CHAR(1) NOT NULL, 
		"DATA_RECEIVE_STATUS" CHAR(1) NOT NULL, 
		"FACTORY_DATA_STATUS" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "TB001006" ADD CONSTRAINT "TB001006_PK" PRIMARY KEY
	("PARTS_NO", 
	 "ENGINEERING_PN_REV_NO", 
	 "PREV_PARTS_NO");

ALTER TABLE "TB001007" ADD CONSTRAINT "TB001007_PK" PRIMARY KEY
	("PARENT_PARTS_NO", 
	 "SUB_PARTS_NO", 
	 "ENGINEERING_PS_REV_NO", 
	 "PREV_PARENT_PARTS_NO", 
	 "PREV_SUB_PARTS_NO");

ALTER TABLE "TB002020" ADD CONSTRAINT "TB002020_PK" PRIMARY KEY
	("ECS_PROCESS_ID");
