--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "TB006001" (
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"ATTENTION_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006002" (
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"DICTIONARY_NO" CHAR(3) NOT NULL, 
		"FUNCTION" CHAR(5) NOT NULL, 
		"ITEM_NAME" CHAR(20) NOT NULL, 
		"REPRESENTATIVE_FLAG" CHAR(1) NOT NULL, 
		"DICT_CREATED_DATE" DATE NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006003" (
		"REF_MC_DEV_MDL_CODE" CHAR(4) NOT NULL, 
		"NEW_MC_DEV_MDL_CODE" CHAR(4) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006004" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"REF_MC_DEV_MDL_CODE" CHAR(4) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006005" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"PROD_BASE_CODE" CHAR(1) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006006" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"LINKED_DATE" DATE NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006007" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"LINKED_DATE" DATE NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006008" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"PARTS_NAME" CHAR(20) NOT NULL, 
		"BLOCK_NO" DATE NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"USER_ID" CHAR(10) NOT NULL, 
		"FUNCTION" CHAR(5) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006009" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"FILE_NAME" VARCHAR(100) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "TB006001" ADD CONSTRAINT "TB006001_PK" PRIMARY KEY
	("ITEM_ID_NO");

ALTER TABLE "TB006002" ADD CONSTRAINT "TB006002_PK" PRIMARY KEY
	("ITEM_ID_NO", 
	 "DICTIONARY_NO");

ALTER TABLE "TB006003" ADD CONSTRAINT "TB006003_PK" PRIMARY KEY
	("REF_MC_DEV_MDL_CODE", 
	 "NEW_MC_DEV_MDL_CODE");

ALTER TABLE "TB006004" ADD CONSTRAINT "TB006004_PK" PRIMARY KEY
	("ITEM_ID_NO", 
	 "MC_DEV_MODEL_CODE");

ALTER TABLE "TB006005" ADD CONSTRAINT "TB006005_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "ITEM_ID_NO", 
	 "PROD_BASE_CODE", 
	 "SUPPLIER_CODE");

ALTER TABLE "TB006006" ADD CONSTRAINT "TB006006_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "PARTS_NO");

ALTER TABLE "TB006007" ADD CONSTRAINT "TB006007_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_PARTS_NO");

ALTER TABLE "TB006008" ADD CONSTRAINT "TB006008_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "PARTS_NO", 
	 "PARTS_NAME", 
	 "BLOCK_NO", 
	 "SUPPLIER_CODE", 
	 "USER_ID");

ALTER TABLE "TB006009" ADD CONSTRAINT "TB006009_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "FILE_NAME");

