--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "TB009001" (
		"FMC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"FMC_DEV_MODEL_NAME" VARCHAR(100) NOT NULL, 
		"NEW_SYS_CONTROL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009002" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"FMC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"MC_DEV_MODEL_NAME" VARCHAR(100) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"INSTL_DWG_COMPLETE" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009003" (
		"LIST_CODE" CHAR(4) NOT NULL, 
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009004" (
		"APPLIED_MODEL_CODE" CHAR(4) NOT NULL, 
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009005" (
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"BLOCK_NAME" VARCHAR(100) NOT NULL, 
		"BLOCK_FUNCTION" CHAR(1) NOT NULL, 
		"BODY_UNIT_DIV" CHAR(1) NOT NULL, 
		"USER_ID" CHAR(10) NOT NULL, 
		"PREV_USER_ID" CHAR(10) NOT NULL, 
		"ALTERNATE_DATE" DATE NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009006" (
		"FMC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"DESIGN_SECTION" CHAR(2) NOT NULL, 
		"INT_EXT_DGN_DIV" CHAR(1) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009007" (
		"PROD_BASE_CODE" CHAR(1) NOT NULL, 
		"PROD_BASE_NAME" VARCHAR(100) NOT NULL, 
		"LOCATION_CODE" CHAR(1) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009008" (
		"DESTINATION" CHAR(1) NOT NULL, 
		"DESTINATION_NAME" VARCHAR(100) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009009" (
		"APPLIED_MODEL_CODE" CHAR(4) NOT NULL, 
		"DESTINATION" CHAR(1) NOT NULL, 
		"IMPL_DATE_INPUT_COL" CHAR(1) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009014" (
		"DRAWING_SERIES" CHAR(4) NOT NULL, 
		"DRAWING_BLOCK_NO" CHAR(4) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "TB009001" ADD CONSTRAINT "TB009001_PK" PRIMARY KEY
	("FMC_DEV_MODEL_CODE");

ALTER TABLE "TB009002" ADD CONSTRAINT "TB009002_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE");

ALTER TABLE "TB009003" ADD CONSTRAINT "TB009003_PK" PRIMARY KEY
	("LIST_CODE");

ALTER TABLE "TB009004" ADD CONSTRAINT "TB009004_PK" PRIMARY KEY
	("APPLIED_MODEL_CODE");

ALTER TABLE "TB009005" ADD CONSTRAINT "TB009005_PK" PRIMARY KEY
	("BLOCK_NO");

ALTER TABLE "TB009006" ADD CONSTRAINT "TB009006_PK" PRIMARY KEY
	("FMC_DEV_MODEL_CODE", 
	 "BLOCK_NO");

ALTER TABLE "TB009007" ADD CONSTRAINT "TB009007_PK" PRIMARY KEY
	("PROD_BASE_CODE");

ALTER TABLE "TB009008" ADD CONSTRAINT "TB009008_PK" PRIMARY KEY
	("DESTINATION");

ALTER TABLE "TB009009" ADD CONSTRAINT "TB009009_PK" PRIMARY KEY
	("APPLIED_MODEL_CODE", 
	 "DESTINATION", 
	 "IMPL_DATE_INPUT_COL");

ALTER TABLE "TB009014" ADD CONSTRAINT "TB009014_PK" PRIMARY KEY
	("DRAWING_SERIES", 
	 "DRAWING_BLOCK_NO");

