-- 同指示設通とオーバーフローの代表設通とオーバーフローの同指示設通をまとめて取得するVIEW
CREATE OR REPLACE FORCE VIEW SIMULTANEOUS_OVERFLOW_ECS (
	REPR_ECS_NO,
	REPR_ECS_REV_NO,
	SIMULTANEOUS_ECS_NO,
	SIMULTANEOUS_ECS_ORDER,
	RANK -- 1:同指示設通、2:オーバーフロー設通の代表、3:オーバーフロー設通の同指示設通
)
AS (
	SELECT 
		REPR_ECS_NO,
		REPR_ECS_REV_NO,
		SIMULTANEOUS_ECS_NO,
		ROW_NUMBER() OVER(PARTITION BY REPR_ECS_NO,REPR_ECS_REV_NO ORDER BY OVER_FLOW_REPR_ECS_NO,RANK,SIMULTANEOUS_ECS_ORDER) AS SIMULTANEOUS_ECS_ORDER,
		RANK
	 FROM (
		-- 代表設通からの同指示
		SELECT 
			A.REPR_ECS_NO AS REPR_ECS_NO,
			A.REPR_ECS_REV_NO AS REPR_ECS_REV_NO,
			A.SIMULTANEOUS_ECS_NO AS SIMULTANEOUS_ECS_NO,
			' ' AS OVER_FLOW_REPR_ECS_NO,
			A.SIMULTANEOUS_ECS_ORDER AS SIMULTANEOUS_ECS_ORDER,
			1 AS RANK
		FROM TB003002 A
		-- オーバーフロー設通の代表
		UNION ALL
		SELECT 
			B.OVERFLOW_REPR_ECS_NO,
			(SELECT MAX(C.ECS_REV_NO) FROM TB003001 C WHERE B.ECS_NO = C.ECS_NO GROUP BY C.ECS_NO),
			B.ECS_NO,
			B.ECS_NO,
			1,
			2
		FROM TB003001 B
		WHERE B.OVERFLOW_REPR_ECS_NO <> ''
		-- オーバーフロー設通の同指示
		UNION ALL
		SELECT
			E.OVERFLOW_REPR_ECS_NO,
			(SELECT MAX(F.ECS_REV_NO) FROM TB003001 F WHERE E.ECS_NO = F.ECS_NO GROUP BY F.ECS_NO),
			D.SIMULTANEOUS_ECS_NO,
			E.ECS_NO,
			D.SIMULTANEOUS_ECS_ORDER,
			3
		FROM TB003002 D
		INNER JOIN TB003001 E
			ON D.REPR_ECS_NO = E.ECS_NO 
		WHERE 
			E.OVERFLOW_REPR_ECS_NO <> ''
	) X 
)
