CREATE OR REPLACE FORCE VIEW RELATED_OVERFLOW_ECS (
	REPR_ECS_NO,
	REPR_ECS_REV_NO,
	RELATED_ECS_NO,
	RELATED_ECS_ORDER,
	RANK -- 1:関連設通、2:オーバーフロー設通の関連設通
)
AS  (
	SELECT 
		REPR_ECS_NO,
		REPR_ECS_REV_NO,
		RELATED_ECS_NO,
		ROW_NUMBER() OVER(PARTITION BY REPR_ECS_NO,REPR_ECS_REV_NO ORDER BY OVER_FLOW_REPR_ECS_NO,RANK,RELATED_ECS_ORDER) AS RELATED_ECS_ORDER,
		RANK
	 FROM (
		-- 代表設通からの関連設通
		SELECT 
			A.REPR_ECS_NO AS REPR_ECS_NO,
			A.REPR_ECS_REV_NO AS REPR_ECS_REV_NO,
			A.RELATED_ECS_NO AS RELATED_ECS_NO,
			' ' AS OVER_FLOW_REPR_ECS_NO,
			A.RELATED_ECS_ORDER AS RELATED_ECS_ORDER,
			1 AS RANK
		FROM RELATED_ECS A
		-- オーバーフロー設通の同指示
		UNION ALL
		SELECT
			C.OVERFLOW_REPR_ECS_NO,
			(SELECT MAX(D.ECS_REV_NO) FROM EC_SUMMARY D WHERE C.ECS_NO = D.ECS_NO GROUP BY D.ECS_NO),
			B.RELATED_ECS_NO,
			C.ECS_NO,
			B.RELATED_ECS_ORDER,
			2
		FROM RELATED_ECS B
		INNER JOIN EC_SUMMARY C
			ON B.REPR_ECS_NO = C.ECS_NO 
		WHERE 
			C.OVERFLOW_REPR_ECS_NO <> ''
	) X 
)