--<ScriptOptions statementTerminator=";"/>

CREATE SCHEMA "Schema";

CREATE GLOBAL TEMPORARY TABLE "GT003001" (
		"ECS_NO" CHAR(11) NOT NULL
	)
	ON COMMIT PRESERVE ROWS
	NOT LOGGED ON ROLLBACK DELETE ROWS;

CREATE TABLE "TB001001" (
		"PARTS_NO" CHAR(15) NOT NULL, 
		"PARTS_FUNCTION" CHAR(5) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB001002" (
		"PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PN_REV_NO" CHAR(3) NOT NULL, 
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"START_DATE" DATE NOT NULL, 
		"END_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB001003" (
		"PARTS_NO" CHAR(15) NOT NULL, 
		"PARTS_PROP_REV_NO" CHAR(3) NOT NULL, 
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"START_DATE" DATE NOT NULL, 
		"END_DATE" DATE NOT NULL, 
		"DRAWING_SERIES" CHAR(4) NOT NULL, 
		"DRAWING_BLOCK_NO" CHAR(4) NOT NULL, 
		"DRAWING_OVER" CHAR(1) NOT NULL, 
		"DRAWING_COL" CHAR(1) NOT NULL, 
		"PARTS_NAME" CHAR(20) NOT NULL, 
		"SUPPL_NAME" CHAR(3) NOT NULL, 
		"DRAWING_SYMBOL" CHAR(1) NOT NULL, 
		"MASS" VARCHAR(6) NOT NULL, 
		"METAL_MASS" VARCHAR(6) NOT NULL, 
		"DRAWING_CLASS" CHAR(1) NOT NULL, 
		"THICKNESS" CHAR(5) NOT NULL, 
		"MATERIAL" VARCHAR(48) NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"REPR_OF_MAIN_ECS_NO" CHAR(11) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB001004" (
		"PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"SUB_PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PS_REV_NO" CHAR(3) NOT NULL, 
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"START_DATE" DATE NOT NULL, 
		"END_DATE" DATE NOT NULL, 
		"DRAWING_OVER" CHAR(1) NOT NULL, 
		"DRAWING_SYMBOL" CHAR(1) NOT NULL, 
		"INDEX" CHAR(2) NOT NULL, 
		"KIND" CHAR(1) NOT NULL, 
		"DWG_JDG_CODE" CHAR(1) NOT NULL, 
		"REFERENCE" CHAR(1) NOT NULL, 
		"PS_NAME" CHAR(20) NOT NULL, 
		"QUANTITY" SMALLINT NOT NULL, 
		"DOMESTIC_CAL_CODE" CHAR(1) NOT NULL, 
		"FOREIGN_CAL_CODE" CHAR(1) NOT NULL, 
		"CKD_CLASS" CHAR(1) NOT NULL, 
		"THICKNESS" CHAR(5) NOT NULL, 
		"MATERIAL" CHAR(48) NOT NULL, 
		"AUTOMATIC_SYMBOL" VARCHAR(1) NOT NULL, 
		"REPR_OF_MAIN_ECS_NO" CHAR(11) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB001005" (
		"PARTS_NO" CHAR(15) NOT NULL, 
		"RELATED_PARTS_NO" CHAR(15) NOT NULL, 
		"REL_PN_REV_NO" CHAR(3) NOT NULL, 
		"RELATION_TYPE" CHAR(1) NOT NULL, 
		"START_DATE" DATE NOT NULL, 
		"END_DATE" DATE NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB001006" (
		"PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PN_REV_NO" CHAR(3) NOT NULL, 
		"PREV_PARTS_NO" CHAR(15) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB001007" (
		"PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"SUB_PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PS_REV_NO" CHAR(3) NOT NULL, 
		"PREV_PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"PREV_SUB_PARTS_NO" CHAR(15) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002001" (
		"REPR_ECS_NO" CHAR(11) NOT NULL, 
		"ECS_REV_NO" CHAR(1) NOT NULL, 
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"DRAWING_ORDER" SMALLINT NOT NULL, 
		"DRAWING_NAME" CHAR(20) NOT NULL, 
		"DRAWING_CLASS" CHAR(1) NOT NULL, 
		"REPAIR_PARTS" CHAR(1) NOT NULL, 
		"MFR_LOCAL_CLASS" CHAR(1) NOT NULL, 
		"DWG_JDG_CODE" CHAR(1) NOT NULL, 
		"PAGE_NUMBER" CHAR(2) NOT NULL, 
		"SPEC_DWG_REQ" CHAR(1) NOT NULL, 
		"APPLY_CHG_DESCRIPTION" CHAR(100) NOT NULL, 
		"SCRAPPING_DIE" CHAR(1) NOT NULL, 
		"DIE_MODIFICATION" CHAR(1) NOT NULL, 
		"COST_VARIATION" CHAR(1) NOT NULL, 
		"MASS_VARIATION" CHAR(1) NOT NULL, 
		"OVERFLOW_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002002" (
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"START_DATE" DATE NOT NULL, 
		"END_DATE" DATE NOT NULL, 
		"DRAWING_SERIES" CHAR(4) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"DRAWER" CHAR(1) NOT NULL, 
		"DESIGNER" CHAR(11) NOT NULL, 
		"DRAWING_CODE" CHAR(1) NOT NULL, 
		"DWG_JDG_CODE" CHAR(1) NOT NULL, 
		"PAGE_NUMBER" CHAR(2) NOT NULL, 
		"APPLY" CHAR(160) NOT NULL, 
		"CONFIDENTIAL_CLASS" CHAR(1) NOT NULL, 
		"INTERCHANGEABILITY" CHAR(1) NOT NULL, 
		"IMPORTANCE_SAFTY" CHAR(1) NOT NULL, 
		"REPAIR_PARTS_CLASS" CHAR(1) NOT NULL, 
		"DRAWING_CLASS" CHAR(1) NOT NULL, 
		"ISSUE_REASON" CHAR(1) NOT NULL, 
		"TITLE_NAME" CHAR(17) NOT NULL, 
		"RECEIVED_DATE" DATE NOT NULL, 
		"SIA_TO_SEND_FLAG" CHAR(1) NOT NULL, 
		"SIA_SEND_DATE" DATE NOT NULL, 
		"SEND_CHECK_OFF" CHAR(1) NOT NULL, 
		"MAIN_ECS_NO" CHAR(11) NOT NULL, 
		"REPR_OF_MAIN_ECS_NO" CHAR(11) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"TCMA_DIST_COMMENT" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002003" (
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"ORD_SEC_REV_NO" CHAR(3) NOT NULL, 
		"ORD_SEC_SND_APRV_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002004" (
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"SUPPLIED_SECTION" CHAR(4) NOT NULL, 
		"SUP_SEC_REV_NO" CHAR(3) NOT NULL, 
		"SUP_SEC_DST_APRV_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002005" (
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"REF_DISTRIBUTED" CHAR(4) NOT NULL, 
		"REF_DIST_REV_NO" CHAR(3) NOT NULL, 
		"REF_DIST_DST_APRV_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002006" (
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"SEND_REV_NO" CHAR(3) NOT NULL, 
		"SIA_SEND_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002007" (
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"NOTIFY_REV_NO" CHAR(3) NOT NULL, 
		"NOTIFY_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002008" (
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"TCMA_DELIVER_REV_NO" CHAR(3) NOT NULL, 
		"TCMA_DELIVER_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002009" (
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"TCMA_RECEIVE_REV_NO" CHAR(3) NOT NULL, 
		"TCMA_RECEIVE_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002010" (
		"SYSMTEM_ID" CHAR(4) NOT NULL, 
		"LATEST_CHECK_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002011" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"DWG_CHECK_FLAG" CHAR(1) NOT NULL, 
		"DRAWING_QUANTITY" SMALLINT NOT NULL, 
		"CHECK_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002012" (
		"PARTS_NO" CHAR(15) NOT NULL, 
		"CHECK_DATE" DATE NOT NULL, 
		"NOTIFY_DATE" DATE NOT NULL, 
		"ISSUE_STATUS" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002013" (
		"PARTS_NO" CHAR(15) NOT NULL, 
		"PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"CHECK_DATE" DATE NOT NULL, 
		"DWG_JDG_CODE" CHAR(1) NOT NULL, 
		"SUB_PARTS_ISSUE_STATUS" CHAR(1) NOT NULL, 
		"REPR_FINAL_PARTS_NO" CHAR(15) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002014" (
		"PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"CHECK_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002015" (
		"LIST_CODE" CHAR(4) NOT NULL, 
		"NEED_TO_SEND_FLAG" CHAR(1) NOT NULL, 
		"CHECK_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002016" (
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_REV_NO" CHAR(2) NOT NULL, 
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"CHECK_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002017" (
		"PARTS_NO" CHAR(15) NOT NULL, 
		"PROD_BASE_CODE" CHAR(1) NOT NULL, 
		"SOURCE_TYPE" CHAR(1) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"SUPPLIER_ADOPT_DATE" DATE NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB002018" (
		"PROD_BASE_CODE" CHAR(1) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"INTER_EXTER_CLASS" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003001" (
		"ECS_NO" CHAR(11) NOT NULL, 
		"ECS_REV_NO" CHAR(1) NOT NULL, 
		"ECS_SERIES" CHAR(4) NOT NULL, 
		"SECTION_CODE" CHAR(1) NOT NULL, 
		"SERIAL_NO" CHAR(4) NOT NULL, 
		"REPR_SIMUL_CLASS" CHAR(1) NOT NULL, 
		"ECS_TITLE_JP" VARCHAR(250) NOT NULL, 
		"ECS_TITLE_EN" VARCHAR(300) NOT NULL, 
		"ECS_STATUS" CHAR(2) NOT NULL, 
		"ECS_PUBLIC_STATUS" CHAR(2) NOT NULL, 
		"PRECEDE_FLAG" CHAR(1) NOT NULL, 
		"DESIGN_DEPARTMENT" VARCHAR(30) NOT NULL, 
		"DESIGN_SECTION" VARCHAR(30) NOT NULL, 
		"ARRANGE_CLASS" CHAR(1) NOT NULL, 
		"ATTENTION" CHAR(1) NOT NULL, 
		"URGENCY" CHAR(1) NOT NULL, 
		"DISTRIBUTE_CLASS" CHAR(2) NOT NULL, 
		"APPLIED_MODEL" CHAR(2) NOT NULL, 
		"VEHICLE_CHECK" CHAR(1) NOT NULL, 
		"EG_TM_CHECK" CHAR(1) NOT NULL, 
		"REASON" CHAR(1) NOT NULL, 
		"IMPORTANCE" CHAR(1) NOT NULL, 
		"SYNCHRONOUS_CHANGE" CHAR(1) NOT NULL, 
		"RECEIVED_DATE" DATE NOT NULL, 
		"OVERFLOW_REPR_ECS_NO" CHAR(11) NOT NULL, 
		"ECS_ISSUE_DATE" DATE NOT NULL, 
		"GJ_ECS_RECEIVE_DATE" DATE NOT NULL, 
		"ECS_ISSUE_MEMBER" CHAR(20) NOT NULL, 
		"DESIGN_PHONE_NO" CHAR(4) NOT NULL, 
		"REGULATION" CHAR(5) NOT NULL, 
		"EC_DEMAND_DEPT" CHAR(20) NOT NULL, 
		"EC_APPLY" CHAR(1) NOT NULL, 
		"ARRANGE_REMARKS" VARCHAR(3000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003002" (
		"REPR_ECS_NO" CHAR(11) NOT NULL, 
		"REPR_ECS_REV_NO" CHAR(1) NOT NULL, 
		"SIMULTANEOUS_ECS_NO" CHAR(11) NOT NULL, 
		"SIMULTANEOUS_ECS_ORDER" SMALLINT NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003003" (
		"REPR_ECS_NO" CHAR(11) NOT NULL, 
		"REPR_ECS_REV_NO" CHAR(1) NOT NULL, 
		"RELATED_ECS_NO" CHAR(11) NOT NULL, 
		"RELATED_ECS_ORDER" SMALLINT NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003004" (
		"ECS_NO" CHAR(11) NOT NULL, 
		"ECS_REV_NO" CHAR(1) NOT NULL, 
		"LIST_CODE" CHAR(4) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"REMARKS" VARCHAR(3000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003005" (
		"ECS_SERIES" CHAR(4) NOT NULL, 
		"ECS_MEETING_DATE" DATE NOT NULL, 
		"ECS_MTG_LOCATION" CHAR(4) NOT NULL, 
		"ECS_MEETING_NAME" VARCHAR(200) NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003006" (
		"ECS_MTG_LOCATION" CHAR(4) NOT NULL, 
		"ECS_MTG_LOC_NAME" VARCHAR(200) NOT NULL, 
		"LOCATION_CODE" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003007" (
		"ECS_SERIES" CHAR(4) NOT NULL, 
		"ECS_MEETING_DATE" DATE NOT NULL, 
		"ECS_MTG_LOCATION" CHAR(4) NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"ECS_REV_NO" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003008" (
		"ECS_NO" CHAR(11) NOT NULL, 
		"ECS_REV_NO" CHAR(1) NOT NULL, 
		"APPLIED_MODEL_CODE" CHAR(4) NOT NULL, 
		"DESTINATION" CHAR(1) NOT NULL, 
		"IMPL_DATE_INPUT_COL" CHAR(1) NOT NULL, 
		"APPLIED_MODEL" CHAR(3) NOT NULL, 
		"ECS_IMPL_REV_NO" CHAR(3) NOT NULL, 
		"DISPLAY_ORDER" SMALLINT NOT NULL, 
		"DGN_REQD_START_DATE" CHAR(2) NOT NULL, 
		"ARR_REQD_START_DATE" CHAR(2) NOT NULL, 
		"DECIDED_IMPL_DATE" DATE NOT NULL, 
		"PARTIAL_PENDING_FLAG" CHAR(1) NOT NULL, 
		"PENDING_DECIDED_DATE" DATE NOT NULL, 
		"IMPLEMENT_EVENT_ID" CHAR(6) NOT NULL, 
		"ECS_ISSUE_DATE" DATE NOT NULL, 
		"IMPL_DATE_DECIDED_DATE" DATE NOT NULL, 
		"ECS_MEETING_DATE" DATE NOT NULL, 
		"ECS_MTG_DATE_STATUS" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003009" (
		"ECS_NO" CHAR(11) NOT NULL, 
		"ECS_REV_NO" CHAR(1) NOT NULL, 
		"ECS_ISSUE_REV_NO" CHAR(3) NOT NULL, 
		"ECS_ISSUE_DATE" DATE NOT NULL, 
		"ECS_IMPL_REV_NO" CHAR(3) NOT NULL, 
		"ECS_MEETING_DATE" DATE NOT NULL, 
		"ECS_MTG_DATE_STATUS" CHAR(1) NOT NULL, 
		"DUMMY_ISSUE_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003010" (
		"PARENT_EVENT_ID" CHAR(10) NOT NULL, 
		"EVENT_NAME" VARCHAR(100) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003011" (
		"EVENT_ID" CHAR(6) NOT NULL, 
		"PARENT_EVENT_ID" CHAR(6) NOT NULL, 
		"EVENT_NAME" VARCHAR(100) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003012" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"PROD_BASE_CODE" CHAR(1) NOT NULL, 
		"EVENT_DATE" DATE NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB003013" (
		"ECS_NO" CHAR(11) NOT NULL, 
		"ECS_REV_NO" CHAR(1) NOT NULL, 
		"FILE_NAME" VARCHAR(256) NOT NULL, 
		"FILE_DATA" BLOB NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004001" (
		"PARTS_NO" CHAR(15) NOT NULL, 
		"ENGINEERING_PN_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PN_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PN_STATUS" CHAR(2) NOT NULL, 
		"APPROVED_DATE" DATE NOT NULL, 
		"APPROVER_USER_ID" CHAR(10) NOT NULL, 
		"EDITOR_USER_ID" CHAR(10) NOT NULL, 
		"ADOPT_DATE" DATE NOT NULL, 
		"ABOLISH_DATE" DATE NOT NULL, 
		"TMP_REGIST_DATE" DATE NOT NULL, 
		"PENDING_DECIDED_DATE" DATE NOT NULL, 
		"JOB_SEQ_NO" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PROD_BASE_CODE" CHAR(1) NOT NULL, 
		"DATA_CHECK_RESULT" CHAR(1) NOT NULL, 
		"REPR_OF_MAIN_ECS_NO" CHAR(11) NOT NULL, 
		"SKIP_FLAG" CHAR(1) NOT NULL, 
		"CANCEL_FLAG" CHAR(1) NOT NULL, 
		"PARTS_PROP_REV_NO" CHAR(3) NOT NULL, 
		"TMP_ABOLISH_DATE" DATE NOT NULL, 
		"TMP_CANCEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004002" (
		"SUB_PARTS_NO" CHAR(15) NOT NULL, 
		"PARENT_PARTS_NO" CHAR(15) NOT NULL, 
		"PS_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PS_REV_NO" CHAR(3) NOT NULL, 
		"FACTORY_PS_STATUS" CHAR(2) NOT NULL, 
		"APPROVED_DATE" DATE NOT NULL, 
		"APPROVER_USER_ID" CHAR(10) NOT NULL, 
		"EDITOR_USER_ID" CHAR(10) NOT NULL, 
		"ADOPT_DATE" DATE NOT NULL, 
		"ABOLISH_DATE" DATE NOT NULL, 
		"TMP_REGIST_DATE" DATE NOT NULL, 
		"PENDING_DECIDED_DATE" DATE NOT NULL, 
		"CONSUMPTION_ROUTING" CHAR(2) NOT NULL, 
		"PROCESSING_CODE" CHAR(1) NOT NULL, 
		"MANAGEMENT_STATUS" CHAR(1) NOT NULL, 
		"SUPPLY_CODE" CHAR(1) NOT NULL, 
		"SHIP_SUPPLY_CLASS" CHAR(1) NOT NULL, 
		"ADOPT_CHECK_CODE" CHAR(1) NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"DATA_CHECK_RESULT" CHAR(1) NOT NULL, 
		"REPR_OF_MAIN_ECS_NO" CHAR(11) NOT NULL, 
		"SKIP_FLAG" CHAR(1) NOT NULL, 
		"CANCEL_FLAG" CHAR(1) NOT NULL, 
		"ENGINEERING_PS_REV_NO" CHAR(3) NOT NULL, 
		"TMP_ABOLISH_DATE" DATE NOT NULL, 
		"TMP_CANCEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004003" (
		"SEQUENCING_NO" CHAR(2) NOT NULL, 
		"SEQUENCING_NAME" VARCHAR(100) NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004004" (
		"MAPPING_NO" CHAR(4) NOT NULL, 
		"NEW_CONS_ROUT_NO" CHAR(2) NOT NULL, 
		"NEW_JOB_SEQ_NO" CHAR(2) NOT NULL, 
		"NEW_UNIT_CLASS" CHAR(1) NOT NULL, 
		"SUPPLIER_CODE_COND" VARCHAR(20) NOT NULL, 
		"NEW_SUPPLY_CODE" CHAR(1) NOT NULL, 
		"NEW_PROCESSING_CODE" CHAR(1) NOT NULL, 
		"PRCSSING_CODE_FOR_CHK" CHAR(1) NOT NULL, 
		"SEPICS_CONS_ROUT_NO" CHAR(4) NOT NULL, 
		"SEPICS_RCV_ROUT_NO" CHAR(4) NOT NULL, 
		"SEPICS_JOB_SEQ_NO" CHAR(4) NOT NULL, 
		"SEPICS_UNIT_CLASS" CHAR(1) NOT NULL, 
		"SEPICS_SUPPLY_CODE" CHAR(1) NOT NULL, 
		"SEPICS_PROCESSING_CODE" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB004005" (
		"PROCESSING_CODE" CHAR(1) NOT NULL, 
		"CONTENTS" VARCHAR(100) NOT NULL, 
		"ORDER_MOVE_DIV" CHAR(1) NOT NULL, 
		"INTER_EXTER_CLASS" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(1000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006001" (
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"ATTENTION_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006002" (
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"DICTIONARY_NO" CHAR(3) NOT NULL, 
		"FUNCTION" CHAR(5) NOT NULL, 
		"ITEM_NAME" CHAR(20) NOT NULL, 
		"REPRESENTATIVE_FLAG" CHAR(1) NOT NULL, 
		"DICT_CREATED_DATE" DATE NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006003" (
		"REF_MC_DEV_MDL_CODE" CHAR(4) NOT NULL, 
		"NEW_MC_DEV_MDL_CODE" CHAR(4) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006004" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"REF_MC_DEV_MDL_CODE" CHAR(4) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006005" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"PROD_BASE_CODE" CHAR(1) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006006" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"LINKED_DATE" DATE NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006007" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"ITEM_ID_NO" CHAR(6) NOT NULL, 
		"LINKED_DATE" DATE NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006008" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"PARTS_NAME" CHAR(20) NOT NULL, 
		"BLOCK_NO" DATE NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"USER_ID" CHAR(10) NOT NULL, 
		"FUNCTION" CHAR(5) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB006009" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"FILE_NAME" VARCHAR(100) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007001" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007002" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(4) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"COL_NO" SMALLINT NOT NULL, 
		"WORK_ORDER_NO" CHAR(10) NOT NULL, 
		"MODEL_CODE" CHAR(7) NOT NULL, 
		"SELECT_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007003" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"LINE_NO" SMALLINT NOT NULL, 
		"MODEL" CHAR(4) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"WORK_NO" CHAR(10) NOT NULL, 
		"LINE_ID" CHAR(3) NOT NULL, 
		"CONTROL_NO" CHAR(4) NOT NULL, 
		"SPECIAL_MARK" CHAR(1) NOT NULL, 
		"HISTORY" CHAR(1) NOT NULL, 
		"LEVEL" SMALLINT NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"REV_NO" CHAR(2) NOT NULL, 
		"PARTS_NAME" VARCHAR(20) NOT NULL, 
		"PURCHASER" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PREPARATION" CHAR(1) NOT NULL, 
		"MAN_HOUR" CHAR(1) NOT NULL, 
		"QUANTITY" CHAR(80) NOT NULL, 
		"DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"CAL_CODE" CHAR(1) NOT NULL, 
		"SIA_CAL_CODE" CHAR(1) NOT NULL, 
		"CKD_CLASS" CHAR(1) NOT NULL, 
		"MASS" CHAR(6) NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"FIRST_MODEL_DUE_DATE" DATE NOT NULL, 
		"DELIVERY_QUANTITY" SMALLINT NOT NULL, 
		"ARRANGEMENT_SIGN" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(200) NOT NULL, 
		"REV_REMARKS" VARCHAR(200) NOT NULL, 
		"MATERIAL_DESCRIPTION" CHAR(40) NOT NULL, 
		"DWG_ISSUE_PLAN_DATE" DATE NOT NULL, 
		"CONTENTS" CHAR(6) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007004" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(4) NOT NULL, 
		"EVENT_MODEL_CODE" CHAR(7) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007005" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"LINE_ID" CHAR(3) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"MODEL" CHAR(4) NOT NULL, 
		"WORK_NO" CHAR(10) NOT NULL, 
		"CONTROL_NO" CHAR(4) NOT NULL, 
		"SPECIAL_MARK" CHAR(1) NOT NULL, 
		"HISTORY" CHAR(1) NOT NULL, 
		"LEVEL" SMALLINT NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"REV_NO" CHAR(2) NOT NULL, 
		"PARTS_NAME" VARCHAR(20) NOT NULL, 
		"PURCHASER" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PREPARATION" CHAR(1) NOT NULL, 
		"MAN_HOUR" CHAR(1) NOT NULL, 
		"DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"CAL_CODE" CHAR(1) NOT NULL, 
		"SIA_CAL_CODE" CHAR(1) NOT NULL, 
		"CKD_CLASS" CHAR(1) NOT NULL, 
		"FIRST_MODEL_DUE_DATE" DATE NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"ARRANGEMENT_SIGN" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(200) NOT NULL, 
		"REV_REMARKS" VARCHAR(200) NOT NULL, 
		"MATERIAL_DESCRIPTION" CHAR(40) NOT NULL, 
		"DWG_ISSUE_PLAN_DATE" DATE NOT NULL, 
		"MFG_SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"MFG_DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"MFG_DUE_DATE" DATE NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007006" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"SHEET_CODE" CHAR(5) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"LINE_ID" CHAR(3) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"EVENT_MODEL_CODE" CHAR(7) NOT NULL, 
		"QUANTITY" SMALLINT NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007007" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"CHANGE_REV_NO" CHAR(3) NOT NULL, 
		"CHANGE_STATUS" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007008" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"LEVEL" SMALLINT NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"DUE_DATE" DATE NOT NULL, 
		"SUMMARY_SYMBOL" CHAR(1) NOT NULL, 
		"CHANGE_REV_NO" CHAR(3) NOT NULL, 
		"TRL_CHANGE_SYMBOL" CHAR(1) NOT NULL, 
		"MFG_CHANGE_SYMBOL" CHAR(1) NOT NULL, 
		"REV_NOTIFY_NO" CHAR(2) NOT NULL, 
		"SPECIAL_MARK" CHAR(1) NOT NULL, 
		"PURCHASER" CHAR(2) NOT NULL, 
		"SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"PARTS_NAME" CHAR(20) NOT NULL, 
		"TRL_SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"PARTS_REV_NO" CHAR(3) NOT NULL, 
		"ECS_NO" CHAR(11) NOT NULL, 
		"TRL_DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"DWG_PARTS_NO" CHAR(15) NOT NULL, 
		"DWG_PARTS_REV_NO" CHAR(3) NOT NULL, 
		"DWG_ECS_NO" CHAR(11) NOT NULL, 
		"DWG_SUPPLIER_CODE" CHAR(4) NOT NULL, 
		"DWG_CONS_ROUT" CHAR(4) NOT NULL, 
		"PRD_QLT_REMARKS" VARCHAR(100) NOT NULL, 
		"CAL_CODE" CHAR(1) NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"CKD_CLASS" CHAR(1) NOT NULL, 
		"ARRANGEMENT_SIGN" CHAR(1) NOT NULL, 
		"CHANGE_REASON" CHAR(100) NOT NULL, 
		"DISPLAY_ORDER" SMALLINT NOT NULL, 
		"FUNCTION" CHAR(5) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007009" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"LEVEL" SMALLINT NOT NULL, 
		"EVENT_PARTS_NO" CHAR(15) NOT NULL, 
		"SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"DUE_DATE" DATE NOT NULL, 
		"SUMMARY_SYMBOL" CHAR(1) NOT NULL, 
		"CHANGE_REV_NO" CHAR(3) NOT NULL, 
		"EVENT_MODEL_CODE" CHAR(7) NOT NULL, 
		"QUANTITY" SMALLINT NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007010" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"TRL_SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"MFG_SUPPLY_SECTION" CHAR(5) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB007011" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"EVENT_ID" CHAR(6) NOT NULL, 
		"TRL_DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"MFG_DELIVERY_LOCATION" CHAR(2) NOT NULL, 
		"DUE_DATE" DATE NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"PROD_BASE_CODE" CHAR(1)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008001" (
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"FINAL_OVER" CHAR(1) NOT NULL, 
		"REPR_SERIES_CLASS" CHAR(3) NOT NULL, 
		"SERIES_CLASS_DIFF" CHAR(1) NOT NULL, 
		"STRUCT_BLK_REGIST_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008002" (
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"FINAL_OVER" CHAR(1) NOT NULL, 
		"COMBINED_INDEX" CHAR(30) NOT NULL, 
		"KIND" CHAR(1) NOT NULL, 
		"FACTORY_NEW_KEY" CHAR(2) NOT NULL, 
		"STRUCTURE_REV_NO" CHAR(2) NOT NULL, 
		"DRAWING_NO" CHAR(15) NOT NULL, 
		"DRAWING_LEVEL" CHAR(1) NOT NULL, 
		"REFERENCE" CHAR(1) NOT NULL, 
		"SERIES_CLASS" CHAR(3) NOT NULL, 
		"ECS_NO_NOW" CHAR(5) NOT NULL, 
		"DWG_NO_FOR_PARTS" CHAR(15) NOT NULL, 
		"BLOCK_ITEM" CHAR(40) NOT NULL, 
		"SUPPLMENTARY_CLASS" CHAR(1) NOT NULL, 
		"CAL_CODE" CHAR(2) NOT NULL, 
		"REVISION_NO" CHAR(2) NOT NULL, 
		"DRAWING_CODE" CHAR(1) NOT NULL, 
		"DRAWER" CHAR(1) NOT NULL, 
		"DWG_JDG_CODE" CHAR(1) NOT NULL, 
		"IMPORTANCE_SAFTY" CHAR(1) NOT NULL, 
		"CONSPUMTION_ROUTING" CHAR(4) NOT NULL, 
		"RECEIVE_DELIVER_SEQ" CHAR(4) NOT NULL, 
		"JOB_SEQUENCING" CHAR(4) NOT NULL, 
		"DESIGN_PER_CAR_QTY" CHAR(4) NOT NULL, 
		"FACTORY_PER_CAR_QTY" CHAR(4) NOT NULL, 
		"DWG_NO_FOR_SUB_PARTS" CHAR(15) NOT NULL, 
		"OVER_FOR_SUB_PARTS" CHAR(1) NOT NULL, 
		"INDEX_FOR_SUB_PARTS" CHAR(2) NOT NULL, 
		"KIND_FOR_SUB_PARTS" CHAR(1) NOT NULL, 
		"SYMBOL" CHAR(1) NOT NULL, 
		"STURCT_REGIST_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008003" (
		"LIST_CODE" CHAR(4) NOT NULL, 
		"MASSPRO_TRIAL_DIV" CHAR(1) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"DESIGNER" CHAR(11) NOT NULL, 
		"PHONE_NUMBER" CHAR(4) NOT NULL, 
		"AL_BLK_ECS_NO_NOW" CHAR(5) NOT NULL, 
		"AL_BLOCK_SYMBOL" CHAR(1) NOT NULL, 
		"DELETE_FLAG" CHAR(1) NOT NULL, 
		"AL_BLOCK_REGIST_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008004" (
		"LIST_CODE" CHAR(4) NOT NULL, 
		"MASSPRO_TRIAL_DIV" CHAR(1) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"FINAL_PARTS_NO" CHAR(15) NOT NULL, 
		"AL_REV_NO" CHAR(2) NOT NULL, 
		"SPEC_CLASS" CHAR(1) NOT NULL, 
		"PARALLEL_SEQUENCING" CHAR(1) NOT NULL, 
		"APPLY_CLASS" CHAR(1) NOT NULL, 
		"COLOR" CHAR(5) NOT NULL, 
		"DESTINATION_1" CHAR(2) NOT NULL, 
		"DESTINATION_2" CHAR(2) NOT NULL, 
		"DESTINATION_3" CHAR(2) NOT NULL, 
		"DESTINATION_4" CHAR(2) NOT NULL, 
		"DESTINATION_5" CHAR(2) NOT NULL, 
		"OPTION_1" CHAR(5) NOT NULL, 
		"OPTION_2" CHAR(5) NOT NULL, 
		"OPTION_3" CHAR(5) NOT NULL, 
		"OPTION_4" CHAR(5) NOT NULL, 
		"AL_ADOPT_DATE" DATE NOT NULL, 
		"AL_ABOLISH_DATE" DATE NOT NULL, 
		"APPLIED_NO" CHAR(95) NOT NULL, 
		"APP_MDL_ECS_NO_NOW" CHAR(5) NOT NULL, 
		"DESIGN_MEMO" CHAR(10) NOT NULL, 
		"FACTORY_MEMO" CHAR(20) NOT NULL, 
		"KEY1_FINAL_PARTS_NO" CHAR(15) NOT NULL, 
		"SERIES_CLASS" CHAR(3) NOT NULL, 
		"FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"KEY3_LIST_CODE" CHAR(4) NOT NULL, 
		"KEY3_MASSPRO_TRIAL_DIV" CHAR(1) NOT NULL, 
		"KEY3_BLOCK_NO" CHAR(4) NOT NULL, 
		"KEY3_REPR_SERIES_CLASS" CHAR(3) NOT NULL, 
		"KEY3_SERIES_CLASS_DIFF" CHAR(1) NOT NULL, 
		"KEY3_OVER" CHAR(1) NOT NULL, 
		"KEY3_COLUMN" CHAR(1) NOT NULL, 
		"KEY3_COLOR_DIFF" CHAR(2) NOT NULL, 
		"KEY4_LIST_CODE" CHAR(4) NOT NULL, 
		"KEY4_MASSPRO_TRIAL_DIV" CHAR(1) NOT NULL, 
		"KEY4_BLOCK_NO" CHAR(4) NOT NULL, 
		"KEY2_REPR_SERIES_CLASS" CHAR(3) NOT NULL, 
		"KEY2_SERIES_CLASS_DIFF" CHAR(1) NOT NULL, 
		"KEY2_OVER" CHAR(1) NOT NULL, 
		"KEY2_COLUMN" CHAR(1) NOT NULL, 
		"KEY2_FINAL_PARTS_NO" CHAR(15) NOT NULL, 
		"KEY2_SPEC_CLASS" CHAR(1) NOT NULL, 
		"KEY2_PARALLEL_SEQUENCING" CHAR(1) NOT NULL, 
		"KEY2_AL_REV_NO" CHAR(2) NOT NULL, 
		"EXPLODE_SIGN" CHAR(1) NOT NULL, 
		"DELETE_FLAG" CHAR(1) NOT NULL, 
		"SYMBOL" CHAR(1) NOT NULL, 
		"APP_MDL_REGIST_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008005" (
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"FINAL_OVER" CHAR(1) NOT NULL, 
		"COMBINED_INDEX" CHAR(30) NOT NULL, 
		"KIND" CHAR(1) NOT NULL, 
		"FACTORY_NEW_KEY" CHAR(2) NOT NULL, 
		"STRUCTURE_REV_NO" CHAR(2) NOT NULL, 
		"FACTORY_SERIES" CHAR(4) NOT NULL, 
		"DEMANDER" CHAR(1) NOT NULL, 
		"KEY1_FACTORY_SERIES" CHAR(4) NOT NULL, 
		"KEY1_BLOCK_NO" CHAR(4) NOT NULL, 
		"KEY1_REPR_SERIES_CLASS" CHAR(3) NOT NULL, 
		"KEY1_SERIES_CLASS_DIFF" CHAR(1) NOT NULL, 
		"KEY1_FINAL_OVER" CHAR(1) NOT NULL, 
		"KEY1_LINE_NO" CHAR(5) NOT NULL, 
		"COLOR_GEN_SIGN" CHAR(1) NOT NULL, 
		"FACT_SERIES_REGIST_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008006" (
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"FINAL_OVER" CHAR(1) NOT NULL, 
		"COMBINED_INDEX" CHAR(30) NOT NULL, 
		"KIND" CHAR(1) NOT NULL, 
		"FACTORY_NEW_KEY" CHAR(2) NOT NULL, 
		"STRUCTURE_REV_NO" CHAR(2) NOT NULL, 
		"FACTORY_SERIES" CHAR(4) NOT NULL, 
		"COLOR_DIFF" CHAR(2) NOT NULL, 
		"PL_REV_NO" CHAR(2) NOT NULL, 
		"PARALLEL_SEQUENCING" CHAR(1) NOT NULL, 
		"MASSPRO_KD_CLASS" CHAR(2) NOT NULL, 
		"CONSUMPTION_ROUTING" CHAR(4) NOT NULL, 
		"RECEIVE_DELIVER_SEQ" CHAR(4) NOT NULL, 
		"JOB_SEQUENCING" CHAR(4) NOT NULL, 
		"BASE_PROD" CHAR(2) NOT NULL, 
		"PROCESSING_CODE" CHAR(1) NOT NULL, 
		"MANAGEMENT_STATUS" CHAR(1) NOT NULL, 
		"PL_ADOPT_DATE" DATE NOT NULL, 
		"PL_ABOLISH_DATE" DATE NOT NULL, 
		"SUPPLY_CODE" CHAR(1) NOT NULL, 
		"SHIP_SUPPLY_CLASS" CHAR(1) NOT NULL, 
		"UNIT_CLASS" CHAR(1) NOT NULL, 
		"ADOPT_CHECK_CODE" CHAR(1) NOT NULL, 
		"ARRANGE_CLASS" CHAR(1) NOT NULL, 
		"PARTS_GROUP" CHAR(2) NOT NULL, 
		"PARTS_ID" CHAR(4) NOT NULL, 
		"BLOCK_ITEM" CHAR(40) NOT NULL, 
		"INT_EXT_DIV" CHAR(1) NOT NULL, 
		"SUPPLY_SECTION_1" CHAR(5) NOT NULL, 
		"SUPPLY_SECTION_2" CHAR(5) NOT NULL, 
		"SUPPLY_SECTION_3" CHAR(5) NOT NULL, 
		"SUPPLY_SECTION_4" CHAR(5) NOT NULL, 
		"LINE_CLASS_1" CHAR(1) NOT NULL, 
		"LINE_CLASS_2" CHAR(1) NOT NULL, 
		"LINE_CLASS_3" CHAR(1) NOT NULL, 
		"LINE_CLASS_4" CHAR(1) NOT NULL, 
		"PROD_LINE_CLASS_1" CHAR(1) NOT NULL, 
		"PROD_LINE_CLASS_2" CHAR(1) NOT NULL, 
		"PROD_LINE_CLASS_3" CHAR(1) NOT NULL, 
		"PROD_LINE_CLASS_4" CHAR(1) NOT NULL, 
		"KEY2_ECS_NO_NOW" CHAR(5) NOT NULL, 
		"KEY2_FACTORY_SERIES" CHAR(4) NOT NULL, 
		"KEY2_BLOCK_NO" CHAR(4) NOT NULL, 
		"KEY2_FINAL_TITLE_DWG_NO" CHAR(15) NOT NULL, 
		"KEY2_FINAL_OVER" CHAR(1) NOT NULL, 
		"KEY2_COMBINED_INDEX" CHAR(30) NOT NULL, 
		"KEY2_KIND" CHAR(1) NOT NULL, 
		"KEY2_FACTORY_NEW_KEY" CHAR(2) NOT NULL, 
		"KEY2_STRUCTURE_REV_NO" CHAR(2) NOT NULL, 
		"KEY2_COLOR_DIFF" CHAR(2) NOT NULL, 
		"KEY2_PL_REV_NO" CHAR(2) NOT NULL, 
		"KEY2_PARALLEL_SEQUENCING" CHAR(1) NOT NULL, 
		"KEY2_MASSPRO_KD_CLASS" CHAR(2) NOT NULL, 
		"PL_PLAN_COLOR_GEN_SIGN" CHAR(1) NOT NULL, 
		"AUTOMATIC_ID" CHAR(1) NOT NULL, 
		"CARRY_FORWARD_NUM" CHAR(1) NOT NULL, 
		"PL_PLAN_SYMBOL" CHAR(1) NOT NULL, 
		"PL_PLAN_REGIST_DATE" DATE NOT NULL, 
		"PARTS_NO" CHAR(15) NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(1) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB008007" (
		"BATCH_ID" CHAR(10) NOT NULL, 
		"SEND_HOST" CHAR(8) NOT NULL, 
		"RECEIVE_HOST" CHAR(8) NOT NULL, 
		"OPERATION_TYPE" CHAR(1) NOT NULL, 
		"DATA_KIND" CHAR(8) NOT NULL, 
		"CREATE_UPDATE_TIMESTAMP" TIMESTAMP NOT NULL, 
		"RECORD_NUMBER" CHAR(7) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009001" (
		"FMC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"FMC_DEV_MODEL_NAME" VARCHAR(100) NOT NULL, 
		"NEW_SYS_CONTROL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009002" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"FMC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"MC_DEV_MODEL_NAME" VARCHAR(100) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"INSTL_DWG_COMPLETE" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009003" (
		"LIST_CODE" CHAR(4) NOT NULL, 
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009004" (
		"APPLIED_MODEL_CODE" CHAR(4) NOT NULL, 
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009005" (
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"BLOCK_NAME" VARCHAR(100) NOT NULL, 
		"BLOCK_FUNCTION" CHAR(1) NOT NULL, 
		"BODY_UNIT_DIV" CHAR(1) NOT NULL, 
		"USER_ID" CHAR(10) NOT NULL, 
		"PREV_USER_ID" CHAR(10) NOT NULL, 
		"ALTERNATE_DATE" DATE NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009006" (
		"FMC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"BLOCK_NO" CHAR(4) NOT NULL, 
		"DESIGN_SECTION" CHAR(2) NOT NULL, 
		"INT_EXT_DGN_DIV" CHAR(1) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009007" (
		"PROD_BASE_CODE" CHAR(1) NOT NULL, 
		"PROD_BASE_NAME" VARCHAR(100) NOT NULL, 
		"LOCATION_CODE" CHAR(1) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009008" (
		"DESTINATION" CHAR(1) NOT NULL, 
		"DESTINATION_NAME" VARCHAR(100) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009009" (
		"MC_DEV_MODEL_CODE" CHAR(4) NOT NULL, 
		"APPLIED_MODEL_CODE" CHAR(4) NOT NULL, 
		"DESTINATION" CHAR(1) NOT NULL, 
		"IMPL_DATE_INPUT_COL" CHAR(1) NOT NULL, 
		"LOGICAL_DEL_FLAG" CHAR(1) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB009014" (
		"DRAWING_SERIES" CHAR(4) NOT NULL, 
		"DRAWING_BLOCK_NO" CHAR(4) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011001" (
		"ORGANIZATION_CODE" CHAR(6) NOT NULL, 
		"DEPARTMENT_CODE" CHAR(2) NOT NULL, 
		"DEPARTMENT_NAME" VARCHAR(60) NOT NULL, 
		"SECTION_CODE" CHAR(2) NOT NULL, 
		"SECTION_NAME" VARCHAR(60) NOT NULL, 
		"TEAM_CODE" CHAR(2) NOT NULL, 
		"TEAM_NAME" VARCHAR(60) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011002" (
		"USER_ID" CHAR(10) NOT NULL, 
		"EMPLOYEE_NO" CHAR(8) NOT NULL, 
		"KANJI_NAME" VARCHAR(30) NOT NULL, 
		"ROMAN_NAME" VARCHAR(60) NOT NULL, 
		"KANA_NAME" CHAR(60) NOT NULL, 
		"ORGANIZATION_CODE" CHAR(6) NOT NULL, 
		"E_MAIL_ADDRESS" VARCHAR(256) NOT NULL, 
		"PHONE_NO" CHAR(15) NOT NULL, 
		"LANGUAGE_CODE" CHAR(2) NOT NULL, 
		"ROLE_ID" CHAR(10) NOT NULL, 
		"AUTO_DEL_EXCEPT_FLAG" CHAR(6) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATE_UPDATE_DATE" DATE NOT NULL, 
		"AUTH_STOP_DATE" DATE NOT NULL, 
		"AUTOMATIC_SYMBOL" CHAR(5) NOT NULL, 
		"SESSION_ID" VARCHAR(104) NOT NULL, 
		"LOGIN_TIME" TIMESTAMP NOT NULL, 
		"LOGOUT_TIME" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011003" (
		"ROLE_ID" CHAR(10) NOT NULL, 
		"ROLE_NAME" VARCHAR(100) NOT NULL, 
		"REMARKS" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011004" (
		"DOMAIN_ID" CHAR(10) NOT NULL, 
		"DOMAIN_NAME" VARCHAR(120) NOT NULL, 
		"DOMAIN_ORDER" SMALLINT NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011005" (
		"SCREEN_ID" CHAR(10) NOT NULL, 
		"SCREEN_NAME" VARCHAR(120) NOT NULL, 
		"DOMAIN_ID" CHAR(10) NOT NULL, 
		"MENU_DISPLAY_FLAG" CHAR(1) NOT NULL, 
		"SCREEN_ORDER" SMALLINT NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011006" (
		"ROLE_ID" CHAR(10) NOT NULL, 
		"SCREEN_ID" CHAR(10) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011007" (
		"SCREEN_EVENT_ID" CHAR(10) NOT NULL, 
		"SCREEN_ID" CHAR(10) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011008" (
		"ROLE_ID" CHAR(10) NOT NULL, 
		"SCREEN_EVENT_ID" CHAR(10) NOT NULL, 
		"AUTH_CONTROL_KIND" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011009" (
		"ROLE_ID" CHAR(10) NOT NULL, 
		"SCREEN_ID" CHAR(10) NOT NULL, 
		"SCREEN_ITEM_ID" CHAR(30) NOT NULL, 
		"AUTH_CONTROL_KIND" CHAR(1) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011010" (
		"BATCH_ID" CHAR(10) NOT NULL, 
		"BATCH_NAME" VARCHAR(100) NOT NULL, 
		"PATH" VARCHAR(256) NOT NULL, 
		"EXCLUSIVE_BATCH_ID" VARCHAR(100) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011011" (
		"BATCH_SEQ" CHAR(30) NOT NULL, 
		"BATCH_ID" CHAR(10) NOT NULL, 
		"BATCH_PARAMETER" VARCHAR(1000) NOT NULL, 
		"BATCH_STATUS" CHAR(1) NOT NULL, 
		"BATCH_REQUEST_TIME" TIMESTAMP NOT NULL, 
		"BATCH_START_TIME" TIMESTAMP NOT NULL, 
		"BATCH_END_TIME" TIMESTAMP NOT NULL, 
		"REQUEST_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011012" (
		"MAIL_SEND_CONTROL_NO" CHAR(30) NOT NULL, 
		"MAIL_TEMPLATE_ID" CHAR(10) NOT NULL, 
		"SENDER_MAIL_ADDRESS" VARCHAR(256) NOT NULL, 
		"MAIL_SEND_STATUS" CHAR(1) NOT NULL, 
		"MAIL_SEND_MODE" CHAR(1) NOT NULL, 
		"MAIL_REGISTER_TIME" TIMESTAMP NOT NULL, 
		"MAIL_SEND_TIME" TIMESTAMP NOT NULL, 
		"MAIL_BODY" CLOB(2000000) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011013" (
		"MAIL_SEND_CONTROL_NO" CHAR(30) NOT NULL, 
		"ADDRESS_KIND" CHAR(1) NOT NULL, 
		"SENDER_NO" SMALLINT NOT NULL, 
		"RECEIVER_MAIL_ADDRESS" VARCHAR(256) NOT NULL, 
		"MAIL_SEND_STATUS" CHAR(1) NOT NULL, 
		"MAIL_SEND_TIME" TIMESTAMP NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011014" (
		"APPLICATION_NO" CHAR(10) NOT NULL, 
		"KEY_1" CHAR(15) NOT NULL, 
		"KEY_2" CHAR(15) NOT NULL, 
		"KEY_3" CHAR(15) NOT NULL, 
		"KEY_4" CHAR(15) NOT NULL, 
		"KEY_5" CHAR(15) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "TB011015" (
		"CODE_GROUP_ID" CHAR(10) NOT NULL, 
		"CODE_VALUE" CHAR(10) NOT NULL, 
		"JP_DISPLAY_NAME" VARCHAR(300) NOT NULL, 
		"EN_DISPLAY_NAME" VARCHAR(100) NOT NULL, 
		"CODE_GROUP_CLASS" CHAR(1) NOT NULL, 
		"CODE_GROUP_DESCRIPTION" VARCHAR(600) NOT NULL, 
		"CODE_VALUE_DESCRIPTION" VARCHAR(600) NOT NULL, 
		"CREATED_USER_ID" CHAR(10) NOT NULL, 
		"CREATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"CREATED_TIMESTAMP" TIMESTAMP NOT NULL, 
		"UPDATED_USER_ID" CHAR(10) NOT NULL, 
		"UPDATED_APP_EVENT_ID" CHAR(10) NOT NULL, 
		"UPDATED_TIMESTAMP" TIMESTAMP NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "TB001001" ADD CONSTRAINT "TB001001_PK" PRIMARY KEY
	("PARTS_NO");

ALTER TABLE "TB001002" ADD CONSTRAINT "TB001002_PK" PRIMARY KEY
	("PARTS_NO", 
	 "ENGINEERING_PN_REV_NO");

ALTER TABLE "TB001003" ADD CONSTRAINT "TB001003_PK" PRIMARY KEY
	("PARTS_NO", 
	 "PARTS_PROP_REV_NO");

ALTER TABLE "TB001004" ADD CONSTRAINT "TB001004_PK" PRIMARY KEY
	("PARENT_PARTS_NO", 
	 "SUB_PARTS_NO", 
	 "ENGINEERING_PS_REV_NO");

ALTER TABLE "TB001005" ADD CONSTRAINT "TB001005_PK" PRIMARY KEY
	("PARTS_NO", 
	 "RELATED_PARTS_NO", 
	 "REL_PN_REV_NO", 
	 "RELATION_TYPE");

ALTER TABLE "TB001006" ADD CONSTRAINT "TB001006_PK" PRIMARY KEY
	("PARTS_NO", 
	 "ENGINEERING_PN_REV_NO", 
	 "PREV_PARTS_NO");

ALTER TABLE "TB001007" ADD CONSTRAINT "TB001007_PK" PRIMARY KEY
	("PARENT_PARTS_NO", 
	 "SUB_PARTS_NO", 
	 "ENGINEERING_PS_REV_NO", 
	 "PREV_PARENT_PARTS_NO", 
	 "PREV_SUB_PARTS_NO");

ALTER TABLE "TB002001" ADD CONSTRAINT "TB002001_PK" PRIMARY KEY
	("REPR_ECS_NO", 
	 "ECS_REV_NO", 
	 "DRAWING_NO");

ALTER TABLE "TB002002" ADD CONSTRAINT "TB002002_PK" PRIMARY KEY
	("DRAWING_NO", 
	 "DRAWING_REV_NO");

ALTER TABLE "TB002003" ADD CONSTRAINT "TB002003_PK" PRIMARY KEY
	("DRAWING_NO", 
	 "DRAWING_REV_NO", 
	 "SUPPLIER_CODE", 
	 "ORD_SEC_REV_NO");

ALTER TABLE "TB002004" ADD CONSTRAINT "TB002004_PK" PRIMARY KEY
	("DRAWING_NO", 
	 "DRAWING_REV_NO", 
	 "SUPPLIED_SECTION", 
	 "SUP_SEC_REV_NO");

ALTER TABLE "TB002005" ADD CONSTRAINT "TB002005_PK" PRIMARY KEY
	("DRAWING_NO", 
	 "DRAWING_REV_NO", 
	 "REF_DISTRIBUTED", 
	 "REF_DIST_REV_NO");

ALTER TABLE "TB002006" ADD CONSTRAINT "TB002006_PK" PRIMARY KEY
	("DRAWING_NO", 
	 "DRAWING_REV_NO", 
	 "SEND_REV_NO");

ALTER TABLE "TB002007" ADD CONSTRAINT "TB002007_PK" PRIMARY KEY
	("DRAWING_NO", 
	 "DRAWING_REV_NO", 
	 "NOTIFY_REV_NO");

ALTER TABLE "TB002008" ADD CONSTRAINT "TB002008_PK" PRIMARY KEY
	("DRAWING_NO", 
	 "DRAWING_REV_NO", 
	 "TCMA_DELIVER_REV_NO");

ALTER TABLE "TB002009" ADD CONSTRAINT "TB002009_PK" PRIMARY KEY
	("DRAWING_NO", 
	 "DRAWING_REV_NO", 
	 "TCMA_RECEIVE_REV_NO");

ALTER TABLE "TB002010" ADD CONSTRAINT "TB002010_PK" PRIMARY KEY
	("SYSMTEM_ID");

ALTER TABLE "TB002011" ADD CONSTRAINT "TB002011_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE");

ALTER TABLE "TB002012" ADD CONSTRAINT "TB002012_PK" PRIMARY KEY
	("PARTS_NO", 
	 "CHECK_DATE");

ALTER TABLE "TB002013" ADD CONSTRAINT "TB002013_PK" PRIMARY KEY
	("PARTS_NO", 
	 "PARENT_PARTS_NO", 
	 "CHECK_DATE");

ALTER TABLE "TB002014" ADD CONSTRAINT "TB002014_PK" PRIMARY KEY
	("PARENT_PARTS_NO", 
	 "MC_DEV_MODEL_CODE", 
	 "CHECK_DATE");

ALTER TABLE "TB002015" ADD CONSTRAINT "TB002015_PK" PRIMARY KEY
	("LIST_CODE");

ALTER TABLE "TB002016" ADD CONSTRAINT "TB002016_PK" PRIMARY KEY
	("DRAWING_NO", 
	 "DRAWING_REV_NO", 
	 "MC_DEV_MODEL_CODE");

ALTER TABLE "TB002017" ADD CONSTRAINT "TB002017_PK" PRIMARY KEY
	("PARTS_NO", 
	 "PROD_BASE_CODE", 
	 "SOURCE_TYPE", 
	 "SUPPLIER_CODE");

ALTER TABLE "TB002018" ADD CONSTRAINT "TB002018_PK" PRIMARY KEY
	("PROD_BASE_CODE", 
	 "SUPPLIER_CODE");

ALTER TABLE "TB003001" ADD CONSTRAINT "TB003001_PK" PRIMARY KEY
	("ECS_REV_NO", 
	 "ECS_NO");

ALTER TABLE "TB003002" ADD CONSTRAINT "TB003002_PK" PRIMARY KEY
	("REPR_ECS_NO", 
	 "REPR_ECS_REV_NO", 
	 "SIMULTANEOUS_ECS_NO");

ALTER TABLE "TB003003" ADD CONSTRAINT "TB003003_PK" PRIMARY KEY
	("REPR_ECS_NO", 
	 "REPR_ECS_REV_NO", 
	 "RELATED_ECS_NO");

ALTER TABLE "TB003004" ADD CONSTRAINT "TB003004_PK" PRIMARY KEY
	("ECS_NO", 
	 "ECS_REV_NO", 
	 "LIST_CODE", 
	 "BLOCK_NO");

ALTER TABLE "TB003005" ADD CONSTRAINT "TB003005_PK" PRIMARY KEY
	("ECS_SERIES", 
	 "ECS_MEETING_DATE", 
	 "ECS_MTG_LOCATION");

ALTER TABLE "TB003006" ADD CONSTRAINT "TB003006_PK" PRIMARY KEY
	("ECS_MTG_LOCATION");

ALTER TABLE "TB003007" ADD CONSTRAINT "TB003007_PK" PRIMARY KEY
	("ECS_SERIES", 
	 "ECS_MEETING_DATE", 
	 "ECS_MTG_LOCATION", 
	 "ECS_NO", 
	 "ECS_REV_NO");

ALTER TABLE "TB003008" ADD CONSTRAINT "TB003008_PK" PRIMARY KEY
	("ECS_NO", 
	 "ECS_REV_NO", 
	 "APPLIED_MODEL_CODE", 
	 "DESTINATION", 
	 "IMPL_DATE_INPUT_COL", 
	 "APPLIED_MODEL", 
	 "ECS_IMPL_REV_NO");

ALTER TABLE "TB003009" ADD CONSTRAINT "TB003009_PK" PRIMARY KEY
	("ECS_NO", 
	 "ECS_REV_NO", 
	 "ECS_ISSUE_REV_NO");

ALTER TABLE "TB003010" ADD CONSTRAINT "TB003010_PK" PRIMARY KEY
	("PARENT_EVENT_ID");

ALTER TABLE "TB003011" ADD CONSTRAINT "TB003011_PK" PRIMARY KEY
	("EVENT_ID");

ALTER TABLE "TB003012" ADD CONSTRAINT "TB003012_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "PROD_BASE_CODE");

ALTER TABLE "TB003013" ADD CONSTRAINT "TB003013_PK" PRIMARY KEY
	("ECS_NO", 
	 "ECS_REV_NO");

ALTER TABLE "TB004001" ADD CONSTRAINT "TB004001_PK" PRIMARY KEY
	("PARTS_NO", 
	 "ENGINEERING_PN_REV_NO", 
	 "FACTORY_PN_REV_NO");

ALTER TABLE "TB004002" ADD CONSTRAINT "TB004002_PK" PRIMARY KEY
	("SUB_PARTS_NO", 
	 "PARENT_PARTS_NO", 
	 "PS_REV_NO", 
	 "FACTORY_PS_REV_NO");

ALTER TABLE "TB004003" ADD CONSTRAINT "TB004003_PK" PRIMARY KEY
	("SEQUENCING_NO");

ALTER TABLE "TB004004" ADD CONSTRAINT "TB004004_PK" PRIMARY KEY
	("MAPPING_NO");

ALTER TABLE "TB004005" ADD CONSTRAINT "TB004005_PK" PRIMARY KEY
	("PROCESSING_CODE");

ALTER TABLE "TB006001" ADD CONSTRAINT "TB006001_PK" PRIMARY KEY
	("ITEM_ID_NO");

ALTER TABLE "TB006002" ADD CONSTRAINT "TB006002_PK" PRIMARY KEY
	("ITEM_ID_NO", 
	 "DICTIONARY_NO");

ALTER TABLE "TB006003" ADD CONSTRAINT "TB006003_PK" PRIMARY KEY
	("REF_MC_DEV_MDL_CODE", 
	 "NEW_MC_DEV_MDL_CODE");

ALTER TABLE "TB006004" ADD CONSTRAINT "TB006004_PK" PRIMARY KEY
	("ITEM_ID_NO", 
	 "MC_DEV_MODEL_CODE");

ALTER TABLE "TB006005" ADD CONSTRAINT "TB006005_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "ITEM_ID_NO", 
	 "PROD_BASE_CODE", 
	 "SUPPLIER_CODE");

ALTER TABLE "TB006006" ADD CONSTRAINT "TB006006_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "PARTS_NO");

ALTER TABLE "TB006007" ADD CONSTRAINT "TB006007_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_PARTS_NO");

ALTER TABLE "TB006008" ADD CONSTRAINT "TB006008_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "PARTS_NO", 
	 "PARTS_NAME", 
	 "BLOCK_NO", 
	 "SUPPLIER_CODE", 
	 "USER_ID");

ALTER TABLE "TB006009" ADD CONSTRAINT "TB006009_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "FILE_NAME");

ALTER TABLE "TB007001" ADD CONSTRAINT "TB007001_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID");

ALTER TABLE "TB007002" ADD CONSTRAINT "TB007002_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "REV_NOTIFY_NO", 
	 "COL_NO");

ALTER TABLE "TB007003" ADD CONSTRAINT "TB007003_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "REV_NOTIFY_NO", 
	 "LINE_NO");

ALTER TABLE "TB007004" ADD CONSTRAINT "TB007004_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "EVENT_MODEL_CODE");

ALTER TABLE "TB007005" ADD CONSTRAINT "TB007005_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "BLOCK_NO", 
	 "EVENT_PARTS_NO", 
	 "LINE_ID", 
	 "REV_NOTIFY_NO");

ALTER TABLE "TB007006" ADD CONSTRAINT "TB007006_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "SHEET_CODE", 
	 "BLOCK_NO", 
	 "EVENT_PARTS_NO", 
	 "LINE_ID", 
	 "REV_NOTIFY_NO", 
	 "EVENT_MODEL_CODE");

ALTER TABLE "TB007007" ADD CONSTRAINT "TB007007_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "CHANGE_REV_NO");

ALTER TABLE "TB007008" ADD CONSTRAINT "TB007008_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "BLOCK_NO", 
	 "LEVEL", 
	 "EVENT_PARTS_NO", 
	 "SUPPLY_SECTION", 
	 "DELIVERY_LOCATION", 
	 "DUE_DATE", 
	 "SUMMARY_SYMBOL", 
	 "CHANGE_REV_NO");

ALTER TABLE "TB007009" ADD CONSTRAINT "TB007009_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID", 
	 "BLOCK_NO", 
	 "LEVEL", 
	 "EVENT_PARTS_NO", 
	 "SUPPLY_SECTION", 
	 "DELIVERY_LOCATION", 
	 "DUE_DATE", 
	 "SUMMARY_SYMBOL", 
	 "CHANGE_REV_NO", 
	 "EVENT_MODEL_CODE");

ALTER TABLE "TB007010" ADD CONSTRAINT "TB007010_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID");

ALTER TABLE "TB007011" ADD CONSTRAINT "TB007011_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "EVENT_ID");

ALTER TABLE "TB008001" ADD CONSTRAINT "TB008001_PK" PRIMARY KEY
	("BLOCK_NO", 
	 "FINAL_TITLE_DWG_NO", 
	 "FINAL_OVER");

ALTER TABLE "TB008002" ADD CONSTRAINT "TB008002_PK" PRIMARY KEY
	("BLOCK_NO", 
	 "FINAL_TITLE_DWG_NO", 
	 "FINAL_OVER", 
	 "COMBINED_INDEX", 
	 "KIND", 
	 "FACTORY_NEW_KEY", 
	 "STRUCTURE_REV_NO");

ALTER TABLE "TB008003" ADD CONSTRAINT "TB008003_PK" PRIMARY KEY
	("LIST_CODE", 
	 "MASSPRO_TRIAL_DIV", 
	 "BLOCK_NO");

ALTER TABLE "TB008004" ADD CONSTRAINT "TB008004_PK" PRIMARY KEY
	("LIST_CODE", 
	 "MASSPRO_TRIAL_DIV", 
	 "BLOCK_NO", 
	 "FINAL_PARTS_NO", 
	 "AL_REV_NO", 
	 "SPEC_CLASS", 
	 "PARALLEL_SEQUENCING");

ALTER TABLE "TB008005" ADD CONSTRAINT "TB008005_PK" PRIMARY KEY
	("BLOCK_NO", 
	 "FINAL_TITLE_DWG_NO", 
	 "FINAL_OVER", 
	 "COMBINED_INDEX", 
	 "KIND", 
	 "FACTORY_NEW_KEY", 
	 "STRUCTURE_REV_NO", 
	 "FACTORY_SERIES");

ALTER TABLE "TB008006" ADD CONSTRAINT "TB008006_PK" PRIMARY KEY
	("BLOCK_NO", 
	 "FINAL_TITLE_DWG_NO", 
	 "FINAL_OVER", 
	 "COMBINED_INDEX", 
	 "KIND", 
	 "FACTORY_NEW_KEY", 
	 "STRUCTURE_REV_NO", 
	 "FACTORY_SERIES", 
	 "COLOR_DIFF", 
	 "PL_REV_NO", 
	 "PARALLEL_SEQUENCING", 
	 "MASSPRO_KD_CLASS");

ALTER TABLE "TB008007" ADD CONSTRAINT "TB008007_PK" PRIMARY KEY
	("BATCH_ID");

ALTER TABLE "TB009001" ADD CONSTRAINT "TB009001_PK" PRIMARY KEY
	("FMC_DEV_MODEL_CODE");

ALTER TABLE "TB009002" ADD CONSTRAINT "TB009002_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE");

ALTER TABLE "TB009003" ADD CONSTRAINT "TB009003_PK" PRIMARY KEY
	("LIST_CODE");

ALTER TABLE "TB009004" ADD CONSTRAINT "TB009004_PK" PRIMARY KEY
	("APPLIED_MODEL_CODE");

ALTER TABLE "TB009005" ADD CONSTRAINT "TB009005_PK" PRIMARY KEY
	("BLOCK_NO");

ALTER TABLE "TB009006" ADD CONSTRAINT "TB009006_PK" PRIMARY KEY
	("FMC_DEV_MODEL_CODE", 
	 "BLOCK_NO");

ALTER TABLE "TB009007" ADD CONSTRAINT "TB009007_PK" PRIMARY KEY
	("PROD_BASE_CODE");

ALTER TABLE "TB009008" ADD CONSTRAINT "TB009008_PK" PRIMARY KEY
	("DESTINATION");

ALTER TABLE "TB009009" ADD CONSTRAINT "TB009009_PK" PRIMARY KEY
	("MC_DEV_MODEL_CODE", 
	 "APPLIED_MODEL_CODE", 
	 "DESTINATION", 
	 "IMPL_DATE_INPUT_COL");

ALTER TABLE "TB009014" ADD CONSTRAINT "TB009014_PK" PRIMARY KEY
	("DRAWING_SERIES", 
	 "DRAWING_BLOCK_NO");

ALTER TABLE "TB011001" ADD CONSTRAINT "TB011001_PK" PRIMARY KEY
	("ORGANIZATION_CODE");

ALTER TABLE "TB011002" ADD CONSTRAINT "TB011002_PK" PRIMARY KEY
	("USER_ID");

ALTER TABLE "TB011003" ADD CONSTRAINT "TB011003_PK" PRIMARY KEY
	("ROLE_ID");

ALTER TABLE "TB011004" ADD CONSTRAINT "TB011004_PK" PRIMARY KEY
	("DOMAIN_ID");

ALTER TABLE "TB011005" ADD CONSTRAINT "TB011005_PK" PRIMARY KEY
	("SCREEN_ID");

ALTER TABLE "TB011006" ADD CONSTRAINT "TB011006_PK" PRIMARY KEY
	("ROLE_ID", 
	 "SCREEN_ID");

ALTER TABLE "TB011007" ADD CONSTRAINT "TB011007_PK" PRIMARY KEY
	("SCREEN_EVENT_ID");

ALTER TABLE "TB011008" ADD CONSTRAINT "TB011008_PK" PRIMARY KEY
	("ROLE_ID", 
	 "SCREEN_EVENT_ID");

ALTER TABLE "TB011009" ADD CONSTRAINT "TB011009_PK" PRIMARY KEY
	("ROLE_ID", 
	 "SCREEN_ID", 
	 "SCREEN_ITEM_ID");

ALTER TABLE "TB011010" ADD CONSTRAINT "TB011010_PK" PRIMARY KEY
	("BATCH_ID");

ALTER TABLE "TB011011" ADD CONSTRAINT "TB011011_PK" PRIMARY KEY
	("BATCH_SEQ");

ALTER TABLE "TB011012" ADD CONSTRAINT "TB011012_PK" PRIMARY KEY
	("MAIL_SEND_CONTROL_NO");

ALTER TABLE "TB011013" ADD CONSTRAINT "TB011013_PK" PRIMARY KEY
	("MAIL_SEND_CONTROL_NO", 
	 "ADDRESS_KIND", 
	 "SENDER_NO");

ALTER TABLE "TB011014" ADD CONSTRAINT "TB011014_PK" PRIMARY KEY
	("APPLICATION_NO");

ALTER TABLE "TB011015" ADD CONSTRAINT "TB011015_PK" PRIMARY KEY
	("CODE_GROUP_ID", 
	 "CODE_VALUE");

CREATE VIEW "VW003001" AS
--ï ìYVW003001.sqléQè∆ÅB;

CREATE VIEW "VW003002" AS
--ï ìYVW003002.sqléQè∆ÅB;

